/*
 * DllSidecar — cryptor.h
 * XOR string encryption for compile-time obfuscation.
 * Generator pre-computes encrypted bytes; this header decrypts at runtime.
 *
 * @tunelko — BugAInters 2026
 */

#ifndef CRYPTOR_H
#define CRYPTOR_H

#include <windows.h>

/* ── XOR decrypt in-place ── */

static inline void xor_decrypt(unsigned char *data, DWORD len, unsigned char key) {
    for (DWORD i = 0; i < len; i++)
        data[i] ^= key;
}

/* ── XOR decrypt to separate buffer ── */

static inline void xor_decrypt_to(
    const unsigned char *enc, char *out, DWORD len, unsigned char key)
{
    for (DWORD i = 0; i < len; i++)
        out[i] = (char)(enc[i] ^ key);
    out[len] = '\0';
}

/*
 * Usage pattern in generated code:
 *
 *   // Generated by sidecar.py with --encrypt:
 *   unsigned char enc_user32[] = {0x2f, 0x39, 0x3b, ...};  // "user32.dll" ^ 0x5A
 *   #define ENC_USER32_LEN 10
 *   #define ENC_USER32_KEY 0x5A
 *
 *   // Runtime decryption:
 *   char dec[ENC_USER32_LEN + 1];
 *   xor_decrypt_to(enc_user32, dec, ENC_USER32_LEN, ENC_USER32_KEY);
 *   HMODULE h = p_LoadLibraryA(dec);
 */

/* ── Delayed execution (sandbox evasion) ── */

#ifdef DINVOKE_H
static inline void sc_delay(DWORD ms) {
    LARGE_INTEGER li;
    li.QuadPart = -(LONGLONG)ms * 10000LL;
    typedef LONG (NTAPI *fn_NtDelayExecution)(BOOLEAN Alertable, PLARGE_INTEGER Interval);
    fn_NtDelayExecution pDelay = (fn_NtDelayExecution)dinvoke_get_proc(
        dinvoke_get_module(0x22D3B5EDUL), /* ntdll.dll */
        0x0A49084AUL /* NtDelayExecution */
    );
    if (pDelay) pDelay(FALSE, &li);
}
#else
static inline void sc_delay(DWORD ms) {
    Sleep(ms);
}
#endif

#endif /* CRYPTOR_H */
